/**
 * Maps catalog perfume IDs → actual image paths under /public/perfumes/
 * Images live in:
 *   /perfumes/ENTREGA INMEDIATA🫧/CABALLERO🤵‍♂️/<name>.png
 *   /perfumes/ENTREGA INMEDIATA🫧/DAMA🧖‍♀️/<name>.png
 * Encoded as URL-safe paths for the browser.
 */

const M = (file: string) => `/perfumes/m/${encodeURIComponent(file)}`;
const F = (file: string) => `/perfumes/f/${encodeURIComponent(file)}`;

export const imageMap: Record<string, string> = {
  // ── MASCULINOS ──────────────────────────────────────────────────────────────
  'sauvage-edp-dior':            M('SAUVAGE - DIOR.png'),
  'fahrenheit-dior':             M('EROS - VERSACE.png'), // placeholder fallback
  'eros-flame-versace':          M('EROS FLAME - VERSACE.png'),
  'dylan-blue-versace':          M('DYLAN BLUE - VERSACE.png'),
  'aventus-creed':               M('AVENTUS - CREED.png'),
  'silver-mountain-water-creed': M('SILVER MOUNTAIN - CREED.png'),
  'green-irish-tweed-creed':     M('MILLESIME IMPERIAL - CREED.png'),
  'invictus-victory-pr':         M('VICTORY - INVICTUS.png'),
  'boss-bottled-hugo':           M('BOTTLED CLASICA - BOSS.png'),
  'hugo-energise':               M('ENERGISE - BOSS.png'),
  'aqva-pour-homme':             M('AQVA - BVLGARI.png'),
  'declaration-cartier':         M('DECLARATION - CARTIER.png'),
  'santal-33':                   M('SANTAL 33 - LE LABO.png'),
  'le-male-jpg':                 M('LE MALE - JPG.png'),
  'ultramale-jpg':               M('ULTRAMALE - JEAN PAUL GAULTIER.png'),
  'ombre-leather-tf':            M('OMBRE LEATHER - TOM FORD.png'),
  'ombre-nomade-lv':             M('OMBRE NOMADE - LOUIS VUITTON.png'),
  'one-million-lucky-pr':        M('ONE MILLION LUCKY - PACO RABANNE.png'),
  'invictus-onix-pr':            M('ONIX - INVICTUS.png'),
  'osadia-male-yanbal':          M('OSADIA - YANBAL.png'),
  'polo-red-rl':                 M('POLO RED - RALPH LAURENT.png'),
  'santos-cartier-male':         M('SANTOS - CARTIER.png'),
  'scandal-homme-jpg':           M('SCANDAL MAN - SCANDAL.png'),
  'solo-loewe-male':             M('SOLO - LOEWE.png'),
  'solo-male-yanbal':            M('SOLO - YANBAL.png'),
  'spicebomb-vr':                M('SPICE BOMB - VIKTOR & ROLF.png'),
  'stronger-with-you-ea':        M('STRONGER WITH YOU - LATAFFA.png'),
  'most-wanted-azzaro':          M('THE MOST WANTED - AZZARO.png'),
  'the-one-male-dg':             M('THE ONE - DOLCE AND GABANNA.png'),
  'tommy-hilfiger-male':         M('TOMMY HILFIGER - TOMMY.png'),
  'toy-boy-moschino-male':       M('TOY BOY - MOSCHINO.png'),
  'uomo-valentino-male':         M('UOMO - VALENTINO.png'),
  'victory-invictus-male':       M('VICTORY - INVICTUS.png'),
  'voyage-nautica-male':         M('VOYAGE - NAUTICA.png'),
  'y-ysl-male':                  M('YVES SAINT LAURENT.png'),
  'zlatan-ibrahimovic-male':     M('ZLATAN IBRAHMOVIC.png'),
  // extras masculinos
  'born-roma-valentino':         M('BORN IN ROMA - VALENTINO_.png'),
  'bleu-chanel-male':            M('BLEU - CHANNEL.png'),
  'ch-men-ch':                   M('CH MEN - CAROLINA HERRERA.png'),
  'cool-water-davidoff':         M('COOL WATER - DAVIDOFF.png'),
  'eros-versace':                M('EROS - VERSACE.png'),
  'imagination-lv':              M('IMAGINATION - LOUIS VUITTON_.png'),
  'layton-marly':                M('LAYTON - MARLY.png'),
  'le-beau-jpg':                 M('LE BEAU - JEAN PAUL GAULTIER.png'),
  'loewe-7':                     M('LOEWE 7 - LOEWE .png'),
  'one-million-golden-pr':       M('ONE MILLION GOLDEN OUD - PACO RABANNE.png'),
  'sauvage-elixir-dior':         M('ELIXIR - SAUVAGE.png'),
  'adrenalina-yanbal':           M('ADRENALINA - YANBAL.png'),
  'noir-extreme-tf':             M('NOIR EXTREME - TOM FORD.png'),
  'the-kingdom-lattafa-male':    M('THE KINGDOM POUR HOMME - LATAFFA.png'),
  'centaurus':                   M('CENTAURUS - CREED.png'),
  'ohm-yanbal':                  M('OHM - YANBAL.png'),

  // ── FEMENINOS ───────────────────────────────────────────────────────────────
  'chance-chanel-fem':           F('CHANCE - CHANEL.png'),
  'coco-mademoiselle-chanel':    F('COCO MADMOISELLE - CHANEL.png'),
  'chanel-n5':                   F('CHANEL N5 - CHANEL.png'),
  'good-girl-ch':                F('GOOD GIRL - CAROLINA HERRERA.png'),
  'very-good-girl-ch':           F('VERY GOOD GIRL GLAM - CAROLINA HERRERA.png'),
  '212-vip-rose-ch':             F('212 VIP ROSE - CAROLINA HERRERA.png'),
  '212-vip-fem-ch':              F('212 VIP - CAROLINA HERRERA.png'),
  '212-nyc-fem-ch':              F('212 NYC - CAROLINA HERRERA.png'),
  '212-heroes-fem-ch':           F('212 HEROES - CAROLINA HERRERA.png'),
  'la-vie-est-belle-lancome':    F('LA VIE EST BELLE - LANCOME.png'),
  'miss-dior-edp':               F('MISS DIOR EDP - DIOR.png'),
  'cloud-ag':                    F('CLOUD - ARIANA GRANDE.png'),
  'cloud-pink-ag':               F('CLOUD PINK - ARIANA GRANDE.png'),
  'thank-you-next-ag':           F('THANK YOU NEXT - ARIANA GRANDE.png'),
  'bright-crystal-versace':      F('BRIGHT CRYSTAL - VERSACE.png'),
  'light-blue-dg':               F('LIGHT BLUE - DnG.png'),
  'olympea-pr':                  F('OLYMPEA - PACO RABANNE.png'),
  'la-coste-red-fem':            F('RALPH LAUREN - RALPH.png'),
  'khamrah-lataffa':             F('KHAMRAH - LATAFFA.png'),
  'yara-lataffa':                F('YARA - LATAFFA.png'),
  'yara-candy-lataffa':          F('YARA CANDY - LATAFFA.png'),
  'yara-moi-lataffa':            F('YARA MOI - LATAFFA.png'),
  'haya-lataffa':                F('HAYA - LATAFFA.png'),
  'eclaire-lataffa':             F('ECLAIRE - LATAFFA.png'),
  'nebras-lataffa':              F('NEBRAS - LATAFFA.png'),
  'honor-glory-lataffa':         F('HONOR AND GLORY - LATAFFA.png'),
  'sublime-lataffa':             F('SUBLIME - LATAFFA_.png'),
  'amber-oud-gold-alh':          F('AMBER OUD GOLD - AL HAMARAIN.png'),
  'amber-rouge-orientica':       F('AMBER ROUGE - ORIENTICA.png'),
  'azure-fantasy-orientica':     F('AZURE FANTASY - ORIENTICA.png'),
  'royal-amber-orientica':       F('ROYAL AMBER - ORIENTICA (DORADA).png'),
  'velvet-gold-orientica':       F('VELVET GOLD - ORIENTICA.png'),
  'delina-marly':                F('DELINA - MARLY.png'),
  'aventus-for-her-creed':       F('AVENTUS FOR HER - CREED.png'),
  'love-in-white-creed':         F('LOVE IN WHITE - CREED.png'),
  'queen-of-silk-creed':         F('QUEEN OF SILK - CREED.png'),
  'acqua-di-gioia-armani':       F('ACQUA DI GIOIA - GIORGIO ARMANI.png'),
  'omnia-amethyste-bvlgari':     F('AMETHYSTE OMNIA - BVLGARI.png'),
  'omnia-cristalline-bvlgari':   F('OMNIA CRISTALINE - BVLGARI.png'),
  'her-burberry':                F('BURBERRY HER - BURBERRY.png'),
  'her-elixir-burberry':         F('HER ELIXIR - BURBERRY.png'),
  'donna-valentino':             F('DONNA - VALENTINO.png'),
  'devotion-dg':                 F('DEVOTION - DOLCE AND GABANNA.png'),
  'pineapple-dg':                F('PINEAPPLE - DOLCE AND GABANNA.png'),
  'moon-sparkle-escada':         F('MOON SPARKLE - ESCADA.png'),
  'sorbetto-rosso-escada':       F('SORBETTO ROSSO - ESCADA.png'),
  'funny-moschino':              F('FUNNY - MOCHINO.png'),
  'toy-2-moschino':              F('TOY 2 - MOCHINO.png'),
  'toy-2-bubblegum-moschino':    F('TOY 2 BUBBLEGUM - MOSCHINO.png'),
  'toy-2-pearls-moschino':       F('TOY 2 PEARLS - MOSCHINO.png'),
  'pure-seduction-vs':           F('PURE SEDUCTION - VICTORIA SECRET.png'),
  'coconut-passion-vs':          F('COCONUT PASSION - VICTORIA SECRET.png'),
  'mango-temptation-vs':         F('MANGO TEMPTATION - VICTORIA SECRET.png'),
  'juiced-berry-vs':             F('JUICED BERRY - VICTORIA SECRET.png'),
  'vanilla-lace-vs':             F('VANILLA LACE - VICTORIA SECRET.png'),
  'Arabian-tonka-montale':       F('ARABIAN TONKA - MONTALE.png'),
  'roses-musk-montale':          F('ROSES MUSK - MONTALE.png'),
  'intense-cafe-montale':        F('INTENSE CAFE - MONTALE_.png'),
  'ccori-yanbal':                F('CCORI - YANBAL.png'),
  'gaia-yanbal':                 F('GAIA - YANBAL.png'),
  'cielo-yanbal':                F('CIELO - YANBAL.png'),
  'celos-yanbal':                F('CELOS - YANBAL.png'),
  'osadia-fem-yanbal':           F('OSADIA - YANBAL.png'),
  'il-femme-ilmin':              F('IL FEMME - ILMIN.png'),
  'il-orgasme-ilmin':            F('IL ORGASME - ILMIN.png'),
  'gaultier-divine-jpg':         F('GAULTIER DIVINE - JEAN PAUL GAULTIER.png'),
  'cosmic-power-ct':             F('COSMIC POWER - CHARLOTTE TIBURY.png'),
  'atonic-rose-initio':          F('ATONIC ROSE - INITIO.png'),
  'narcotic-delight-initio':     F('NARCOTIC DELIGHT - INITIO.png'),
  'psychedelic-love-initio':     F('PSYCHEDELIC LOVE - INITIO PARFUMS.png'),
  'meow-katy-perry':             F('MEOW - KATTY PERRY.png'),
  'can-can-paris-hilton':        F('CAN CAN - PARIS HILTON.png'),
  'paris-hilton-fem':            F('PARIS HILTON - PARIS HILTON.png'),
  'candy-yara':                  F('CANDY - YARA.png'),
  'tous-yara':                   F('TOUS - YARA.png'),
  'ari-ag':                      F('ARI - ARIANA GRANDE.png'),
  'eden-juicy-apple-kayaly':     F('EDEN JUICY APPLE - KAYALY.png'),
  'sunkissed-goddess-killian':   F('SUNKISSED GODDESS - KILLIAM.png'),
  'odyssey-candee-armaf':        F('ODYSSEY CANDEE - ARMAF.png'),
  'bleecker-street-bond9':       F('BLEECKER STREET - BOND N9.png'),
  'niche-bharara-fem':           F('NICHE - BHARARA.png'),
  'queen-bharara':               F('QUEEN - BHARARA.png'),
  'guess-fem':                   F('GUESS - GUESS_.png'),
  'ralph-lauren-fem':            F('RALPH LAUREN - RALPH.png'),
  'oud-maracuja-mc':             F('OUD MARACUJA - MAISON CRIVELLI.png'),
  'oud-maracuja':                F('OUD MARACUJA - MAISON CRIVELLI.png'),
  'oud-maracuja-maison-crivelli':F('OUD MARACUJA - MAISON CRIVELLI.png'),
  'karpos-ahli':                 F('KARPOS - AHLI.png'),
  'elixir-shakira':              F('ELIXIR - SHAKIRA.png'),
  '273-beverly-hills':           F('273 - BEVERLY HILLS.png'),
  '360-perry-ellis-fem':         F('360° - PERRY ELLIS.png'),
};

/** Returns the image path for a perfume ID, or undefined (→ falls back to placeholder) */
export function getImagePath(id: string): string | undefined {
  return imageMap[id];
}
