// Carga tu lista actual
const driveItems = [
    // 
    "9PM REBEL - AFNAN", "212 HEROES - CAROLINA HERRERA", "212 MEN NYC - CAROLINA HERRERA", "212 VIP - CAROLINA HERRERA", "360 - PERRY ELLIS",
    "ADRENALINA - YANBAL", "AHLI VEGA - LATAFFA", "AL CONTRARIO - TIZANA TERENZI", "ALEXANDRIA II - XERJOFF", "ALLURE HOME SPORT - CHANNEL",
    "AMBER DUBAI NIGHT - AL HAMARAIN", "ANGELS' SHARE - KILIAN", "AQVA - BVLGARI", "ASAD BOURBON - LATAFFA", "ASSAD - LATAFFA",
    "AVENTUS - CREED", "AZUL - LA COSTE", "AZURE FANTASY - ORIENTICA", "BLACK XS - PACO RABANNE", "BLANC - LA COSTE",
    "BLEECKER STREET - BOND N9", "BLEU - CHANNEL", "BORN IN ROMA - VALENTINO", "BOSS MEN - HUGO BOSS", "BOTTLED CLASICA - BOSS",
    "BVLGARI MAN - BVLGARI", "CEDRAT BOUSE - MANCERA", "CENTAURUS - CREED", "CH MEN - CAROLINA HERRERA", "CLASICA - ONE MILLION",
    "CLUB DE NUIT SILLAGE - ARMAF", "COOL WATER - DAVIDOFF", "DECLARATION - CARTIER", "DESSERT NIGHT - ARMAF", "DIESEL PLUS PLUS - DIESEL",
    "DYLAN BLUE - VERSACE", "EAU DE CARTIER - CARTIER", "EAU FRAICHE - VERSACE", "ELIXIR - SAUVAGE", "EMBLEM - MONTBLANC",
    "EMEER - LATAFFA", "ENERGISE - BOSS", "ERBA PURA - XERJOFF", "EROS - VERSACE", "EROS FLAME - VERSACE", "ESSENCIAL - LA COSTE",
    "ETERNITY - CALVIN KLEIN", "GIVENCHY POUR HOMME", "IL KAKUNO - ILMIN", "IL ORGASME - ILMIN", "IMAGINATION - LOUIS VUITTON",
    "INSURRECTION - REYANE TRADITION", "INVICTUS CLASICA - PACCO RABANNE", "KHAMRAH DUNKHAN - LATAFFA", "KHAMRAH QAHWA - LATAFFA",
    "KING - BHARARA", "L'IMMENSITÉ - LOUIS VUITTON", "L´EAU D'ISSEY MIYAKE", "La coste essential", "LA COSTE RED",
    "LAYTON - MARLY", "LE BEAU - JEAN PAUL GAULTIER", "LE BEAU PARADISE - JPG", "LE MALE - JPG", "LE MALE ELIXIR ABSOLU - JEAN PAUL GAULTIER",
    "LEVAR DEL SOLE - XERJOFF", "LIMONI FRESH - ARMAF", "LOEWE 7 - LOEWE", "MAN EXTREME - BVLGARI", "MAN IN BLACK - BVLGARI",
    "MANDARIN SKY - ARMAF", "MANDARIN SKY ELIXIR - ARMAF", "MARIA FARINA - ROGER & GALLET", "MEGAMARE - ORTO PARASI", "MILLESIME IMPERIAL - CREED",
    "MONTANA HOMME - MONTANA", "NEBRAS - LATAFFA", "NITRO RED - DUMONT", "NOIR EXTREME - TOM FORD", "ODDYSSEY AQUA - ARMAF",
    "OHM - YANBAL", "OMBRE LEATHER - TOM FORD", "OMBRE NOMADE - LOUIS VUITTON", "ONE - CALVIN KLEIN", "ONE MILLION GOLDEN OUD - PACO RABANNE",
    "ONE MILLION LUCKY - PACO RABANNE", "ONIX - INVICTUS", "OPULEND OUD - LATAFFA", "OSADIA - YANBAL", "OUD MARACUJA - MAISON CRIVELLI",
    "OUD OF GLORY - LATAFFA", "POLO RED - RALPH LAURENT", "PROFUMO - AQUA DI GIO", "RA ED SILVER - LATAFFA", "SAFEER - LATAFFA",
    "SANTAL 33 - LE LABO", "SANTOS - CARTIER", "SCANDAL MAN - SCANDAL", "SHANEEN GOLD - LATAFFA", "SILVER MOUNTAIN - CREED",
    "SOLO - LOEWE", "SOLO - YANBAL", "SPICE BOMB - VIKTOR & ROLF", "STARWALKER - MONTBLANC", "STRONGER WITH YOU - LATAFFA",
    "SUMMER HAMMER - LORENZO PAZZAGLIA", "SWISS ARMY - VICTORINOX", "THE KINGDOM POUR HOMME - LATAFFA", "THE MOST WANTED - AZZARO",
    "THE ONE - DOLCE AND GABANNA", "TOMMY HILFIGER - TOMMY", "TOY BOY - MOSCHINO", "ULTRAMALE - JEAN PAUL GAULTIER", "UOMO - VALENTINO",
    "VICTORY - INVICTUS", "VIKING CAIRO - BHARARA", "VIKING SHAMIR - BHARARA", "VOYAGE - NAUTICA", "YVES SAINT LAURENT",
    "OUD AMETHYST - LATAFFA", "212 HEROES - CAROLINA HERRERA", "212 NYC - CAROLINA HERRERA", "212 VIP - CAROLINA HERRERA", "212 VIP ROSE - CAROLINA HERRERA",
    "273 - BEVERLY HILLS", "360° - PERRY ELLIS", "ACQUA DI GIOIA - GIORGIO ARMANI", "AGUA MISTICA - SOL DE JANEIRO", "AMBER DUBAI NIGHT - AL HAMARAIN",
    "AMBER OUD GOLD - AL HAMARAIN", "AMBER ROUGE - ORIENTICA", "AMETHYSTE OMNIA - BVLGARI", "ARABIAN TONKA - MONTALE", "ARI - ARIANA GRANDE",
    "ATONIC ROSE - INITIO", "AVENTUS FOR HER - CREED", "AZURE FANTASY - ORIENTICA", "BFF - KIM KARDASHIAN", "BIANCO LATTE - GARDONI TOSCANA",
    "BLEECKER STREET - BOND N9", "BRIGHT CRYSTAL - VERSACE", "BURBERRY HER - BURBERRY", "CAN CAN - PARIS HILTON", "CANDY - YARA",
    "CCORI - YANBAL", "CELOS - YANBAL", "CHANCE - CHANEL", "CHANEL N5 - CHANEL", "CIELO - YANBAL",
    "CLOUD - ARIANA GRANDE", "CLOUD PINK - ARIANA GRANDE", "COCO MADMOISELLE - CHANEL", "COCONUT PASSION - VICTORIA SECRET", "COSMIC POWER - CHARLOTTE TIBURY",
    "DELINA - MARLY", "DEVOTION - DOLCE AND GABANNA", "DONNA - VALENTINO", "ECLAIRE - LATAFFA", "EDEN JUICY APPLE - KAYALY",
    "ELIXIR - SHAKIRA", "FUNNY - MOCHINO", "GAIA - YANBAL", "GAULTIER DIVINE - JEAN PAUL GAULTIER", "GOOD GIRL - CAROLINA HERRERA",
    "GOOD GIRL BLUSH - CAROLINA HERRRERA", "GUESS - GUESS", "HAYA - LATAFFA", "HER CONFESSION - LATAFFA", "HER ELIXIR - BURBERRY",
    "HONOR AND GLORY - LATAFFA", "IL FEMME - ILMIN", "IL ORGASME - ILMIN", "INTENSE CAFE - MONTALE", "JUICED BERRY - VICTORIA SECRET",
    "KARPOS - AHLI", "KHAMRAH - LATAFFA", "L'ADVENTURE GRAPEFRUIT - AL HAMARAIN", "LA VIE EST BELLE - LANCOME", "LIGHT BLUE - DnG",
    "LOVE IN WHITE - CREED", "MALLOW MADNESS - LATAFFA", "MANGO TEMPTATION - VICTORIA SECRET", "MEOW - KATTY PERRY", "MISS DIOR EDP - DIOR",
    "MOON SPARKLE - ESCADA", "NARCOTIC DELIGHT - INITIO", "NEBRAS - LATAFFA", "NICHE - BHARARA", "ODYSSEY CANDEE - ARMAF",
    "OLYMPEA - PACO RABANNE", "OMNIA AMETHYST - BVLGARI", "OMNIA CRISTALINE - BVLGARI", "OPULEND OUD - LATAFFA", "OSADIA - YANBAL",
    "OUD MARACUJA - MAISON CRIVELLI", "OUD SUBLIME - LATAFFA", "PARIS HILTON - PARIS HILTON", "PINEAPPLE - DOLCE AND GABANNA", "PSYCHEDELIC LOVE - INITIO PARFUMS",
    "PURE SEDUCTION - VICTORIA SECRET", "QUEEN - BHARARA", "QUEEN OF SILK - CREED", "RALPH LAUREN - RALPH", "ROSES MUSK - MONTALE",
    "ROYAL AMBER - ORIENTICA (DORADA)", "SORBETTO ROSSO - ESCADA", "SUBLIME - LATAFFA", "SUNKISSED GODDESS - KILLIAM", "THANK YOU NEXT - ARIANA GRANDE",
    "TOUS - YARA", "TOY 2 - MOCHINO", "TOY 2 BUBBLEGUM - MOSCHINO", "TOY 2 PEARLS - MOSCHINO", "VANILLA LACE - VICTORIA SECRET",
    "VELVET GOLD - ORIENTICA", "VERY GOOD GIRL GLAM - CAROLINA HERRERA", "YARA - LATAFFA", "YARA CANDY - LATAFFA", "YARA MOI - LATAFFA", "YUM YUM - ARMAF"
];

// Esto lo imprime ordenado para que lo copies
console.log("ID;Nombre");
driveItems.forEach(item => {
    console.log(`${item.toLowerCase().replace(/\s+/g, '-')};${item}`);
});