import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#1f1f25",
        "secondary-container": "#af8d11",
        surface: "#131318",
        "secondary-fixed-dim": "#eac249",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#b4c5ff",
        "outline-variant": "#4d4635",
        "error-container": "#93000a",
        "primary-fixed": "#ffe088",
        outline: "#99907c",
        "on-secondary-container": "#352800",
        "surface-dim": "#131318",
        "primary-fixed-dim": "#e9c349",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#ffe08a",
        "on-tertiary-fixed": "#00174b",
        "primary-container": "#d4af37",
        tertiary: "#bfcdff",
        "surface-variant": "#35343a",
        error: "#ffb4ab",
        "tertiary-container": "#97b0ff",
        background: "#131318",
        "surface-container-lowest": "#0e0e13",
        "on-primary-container": "#554300",
        "inverse-primary": "#735c00",
        "inverse-on-surface": "#303036",
        "on-tertiary-fixed-variant": "#27438a",
        "on-primary-fixed": "#241a00",
        "surface-bright": "#39383e",
        "on-surface-variant": "#d0c5af",
        "on-secondary-fixed": "#241a00",
        "on-primary": "#3c2f00",
        "surface-container-low": "#1b1b20",
        "surface-container-high": "#2a292f",
        "inverse-surface": "#e4e1e9",
        "surface-container-highest": "#35343a",
        "on-secondary-fixed-variant": "#574400",
        primary: "#f2ca50",
        "tertiary-fixed": "#dbe1ff",
        secondary: "#eac249",
        "surface-tint": "#e9c349",
        "on-tertiary-container": "#254188",
        "on-tertiary": "#082b72",
        "on-background": "#e4e1e9",
        "on-secondary": "#3d2f00",
        "on-primary-fixed-variant": "#574500",
        "on-surface": "#e4e1e9",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;