import type { Perfume } from '../types';

export const arabesMists: Perfume[] = [
  {
    id: 'khamrah-lattafa',
    name: 'Khamrah',
    brand: 'Lattafa',
    gender: 'U',
    family: 'Ámbar Especiado',
    occasions: ['noche', 'invierno', 'evento'],
    feels: ['dulce', 'especiado', 'gourmand'],
    topNotes: 'Canela, Nuez Moscada, Bergamota',
    heartNotes: 'Dátiles, Praliné, Nardos, Mahonial',
    baseNotes: 'Vainilla, Haba Tonka, Mirra, Madera de Ámbar',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 5,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'Una bandeja de finos dulces envueltos en canela bajo el cielo nocturno del este. Un abrazo de poder y calor absoluto.',
  },
  {
    id: 'khamrah-qahwa',
    name: 'Khamrah Qahwa',
    brand: 'Lattafa',
    gender: 'U',
    family: 'Ámbar Gourmand',
    occasions: ['noche', 'invierno'],
    feels: ['dulce', 'gourmand', 'especiado'],
    topNotes: 'Canela, Cardamomo, Jengibre',
    heartNotes: 'Café, Praliné, Flores Blancas',
    baseNotes: 'Vainilla, Haba Tonka, Benjuí',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 4,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'El mismo poder de Khamrah pero sumergido en un café arábico tostado e hirviente. Implacable, sofisticado y delicioso.',
  },
  {
    id: 'club-de-nuit-intense-man',
    name: 'Club de Nuit Intense',
    brand: 'Armaf',
    gender: 'M',
    family: 'Amaderado Especiado',
    occasions: ['diario', 'trabajo', 'evento'],
    feels: ['amaderado', 'fresco', 'citrico'],
    topNotes: 'Limón, Piña, Grosellas negras',
    heartNotes: 'Abedul, Jazmín, Rosa',
    baseNotes: 'Almizcle, Ámbar gris, Patchouli, Vainilla',
    duration: '10h+',
    avoidTags: ['gourmand', 'dulce-intenso'],
    sweetness: 2,
    freshness: 4,
    intensity: 5,
    emotionalDesc: 'Un líder sin esfuerzo. Cortante como el abedul ahumado y llamativo como la piña ácida.',
  },
  {
    id: 'club-de-nuit-untold',
    name: 'Club de Nuit Untold',
    brand: 'Armaf',
    gender: 'U',
    family: 'Ámbar',
    occasions: ['evento', 'noche', 'cita'],
    feels: ['dulce', 'amaderado'],
    topNotes: 'Azafrán, Jazmín',
    heartNotes: 'Amberwood, Ámbar gris',
    baseNotes: 'Resina de abeto, Cedro',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 5,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'El secreto a voces de las galas exclusivas. Algodón de azúcar ardiente que roba suspiros magnéticos en el aire.',
  },
  {
    id: 'royal-amber-orientica',
    name: 'Royal Amber 💛',
    brand: 'Orientica',
    gender: 'U',
    family: 'Ámbar Vainilla',
    occasions: ['evento', 'noche', 'cita'],
    feels: ['dulce', 'frutal'],
    topNotes: 'Notas verdes, Melón, Piña',
    heartNotes: 'Notas dulces, Jazmín, Vainilla',
    baseNotes: 'Almizcle, Notas amaderadas, Ámbar',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico', 'oud'],
    sweetness: 4,
    freshness: 3,
    intensity: 4,
    emotionalDesc: 'Una corona tallada de ámbar y melón jugoso. La reina opulenta de los perfumes árabes modernos.',
  },
  {
    id: 'velvet-gold-orientica',
    name: 'Velvet Gold 💜',
    brand: 'Orientica',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['evento', 'noche', 'cita'],
    feels: ['floral', 'dulce'],
    topNotes: 'Pimienta rosa, Caramelo, Violeta',
    heartNotes: 'Rosa, Notas atalcadas, Pachulí',
    baseNotes: 'Vainilla, Notas amaderadas',
    duration: '12h+',
    avoidTags: ['citrico', 'fresco', 'polvo'],
    sweetness: 5,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Terciopelo morado cayendo pesado y sensual. Rosa caramelizada con un polvo de oro que paraliza corazones.',
  },
  {
    id: 'opulent-oud-lattafa',
    name: 'Opulent Oud',
    brand: 'Lattafa',
    gender: 'U',
    family: 'Ámbar Amaderada',
    occasions: ['noche', 'invierno'],
    feels: ['oud', 'especiado', 'dulce'],
    topNotes: 'Azafrán, Notas florales, Cítricos',
    heartNotes: 'Oud, Caramelo, Ámbar',
    baseNotes: 'Resinas, Notas amaderadas, Vainilla, Pachulí, Almizcle',
    duration: '12h+',
    avoidTags: ['fresco-ligero'],
    sweetness: 4,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Un tesoro oculto en el desierto. Oud oscuro endulzado con caramelo para una presencia misteriosa y opulenta.',
  },
  {
    id: 'oud-for-glory-lattafa',
    name: 'Bade\'e Al Oud (Oud for Glory)',
    brand: 'Lattafa',
    gender: 'U',
    family: 'Ámbar Amaderada',
    occasions: ['noche', 'invierno', 'evento'],
    feels: ['oud', 'amaderado', 'especiado'],
    topNotes: 'Azafrán, Nuez Moscada, Lavanda',
    heartNotes: 'Oud, Pachulí',
    baseNotes: 'Oud, Pachulí, Almizcle',
    duration: '12h+',
    avoidTags: ['dulce-gourmand', 'fresco'],
    sweetness: 2,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Gloria absoluta y misticismo. Un oud terroso y especiado que proyecta poder y respeto en cada paso.',
  },
  {
    id: 'raed-silver-lattafa',
    name: 'Ra\'ed Silver',
    brand: 'Lattafa',
    gender: 'M',
    family: 'Ámbar Especiada',
    occasions: ['diario', 'trabajo', 'cita'],
    feels: ['fresco', 'especiado', 'dulce'],
    topNotes: 'Mandarina, Canela, Cítricos',
    heartNotes: 'Notas azafranadas, Clavo de olor, Ámbar',
    baseNotes: 'Vainilla, Almizcle, Cuero, Pachulí',
    duration: '8-10h',
    avoidTags: ['acuatico'],
    sweetness: 3,
    freshness: 4,
    intensity: 4,
    emotionalDesc: 'Energía chispeante y sofisticada. Una mezcla de cítricos y canela que evoca dinamismo y elegancia moderna.',
  },
  {
    id: 'safeer-lattafa-unisex',
    name: 'Safeer',
    brand: 'Lattafa',
    gender: 'U',
    family: 'Ámbar Floral',
    occasions: ['diario', 'trabajo'],
    feels: ['fresco', 'verde', 'limpio'],
    topNotes: 'Bergamota, Notas verdes',
    heartNotes: 'Jazmín, Notas florales',
    baseNotes: 'Ámbar, Cedro, Pachulí',
    duration: '8h',
    avoidTags: ['dulce-pesado'],
    sweetness: 2,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'Un embajador de frescura. Notas verdes y ámbar que crean un aura limpia, profesional y equilibrada.',
  },
  {
    id: 'shaheen-gold-lattafa',
    name: 'Shaheen Gold',
    brand: 'Lattafa',
    gender: 'U',
    family: 'Ámbar Frutal',
    occasions: ['diario', 'evento', 'cita'],
    feels: ['frutal', 'dulce', 'fresco'],
    topNotes: 'Piña, Toronja',
    heartNotes: 'Higo, Lavanda',
    baseNotes: 'Vainilla, Haba Tonka, Pachulí',
    duration: '10h+',
    avoidTags: ['oud', 'acuatico'],
    sweetness: 4,
    freshness: 3,
    intensity: 4,
    emotionalDesc: 'Dulzura dorada y tropical. Piña jugosa sobre una base cremosa de vainilla que brilla con luz propia.',
  },
  {
    id: 'the-kingdom-lattafa-male',
    name: 'The Kingdom',
    brand: 'Lattafa',
    gender: 'M',
    family: 'Amaderada Especiada',
    occasions: ['noche', 'evento', 'invierno'],
    feels: ['amaderado', 'especiado', 'dulce'],
    topNotes: 'Lavanda, Azafrán',
    heartNotes: 'Palo de Rosa, Maderas preciosas',
    baseNotes: 'Vainilla, Ámbar',
    duration: '10h+',
    avoidTags: ['fresco-ligero'],
    sweetness: 3,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'El trono del aroma. Maderas intensas y azafrán que construyen una presencia regia e imperante.',
  },
  {
    id: 'viking-cairo-bharara',
    name: 'Viking Cairo',
    brand: 'Bharara',
    gender: 'M',
    family: 'Amaderada Especiada',
    occasions: ['trabajo', 'diario', 'evento'],
    feels: ['fresco', 'especiado', 'amaderado'],
    topNotes: 'Cítricos, Pimienta',
    heartNotes: 'Notas especiadas',
    baseNotes: 'Ámbar, Maderas',
    duration: '12h+',
    avoidTags: ['dulce-gourmand'],
    sweetness: 2,
    freshness: 4,
    intensity: 5,
    emotionalDesc: 'Fuerza extrema para el hombre activo. Una explosión de frescura especiada que dura todo el día.',
  },
  {
    id: 'viking-shamir-bharara',
    name: 'Viking Shamir',
    brand: 'Bharara',
    gender: 'M',
    family: 'Cítrica Aromática',
    occasions: ['diario', 'verano', 'deporte'],
    feels: ['fresco', 'citrico'],
    topNotes: 'Limón, Bergamota',
    heartNotes: 'Notas marinas, Lavanda',
    baseNotes: 'Almizcle, Cedro',
    duration: '10h+',
    avoidTags: ['dulce-pesado'],
    sweetness: 1,
    freshness: 5,
    intensity: 4,
    emotionalDesc: 'Frescura cristalina y duradera. La vitalidad de los cítricos con una proyección mineral impecable.',
  },
  {
    id: 'badee-al-oud-amethyst',
    name: 'Bade\'e Al Oud Amethyst',
    brand: 'Lattafa',
    gender: 'U',
    family: 'Ámbar Vainilla',
    occasions: ['noche', 'cita', 'invierno'],
    feels: ['floral', 'dulce', 'oud'],
    topNotes: 'Pimienta Rosa, Bergamota',
    heartNotes: 'Rosa Turca, Rosa de Bulgaria, Jazmín',
    baseNotes: 'Oud, Vainilla, Ámbar',
    duration: '12h+',
    avoidTags: ['acuatico', 'fresco-ligero'],
    sweetness: 4,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Un velo de seda púrpura. Rosas góticas y oud suavemente endulzado para una sofisticación nocturna.',
  },
  {
    id: 'agua-mistica-mist',
    name: 'Agua Mística',
    brand: 'Touche Body Mist',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'verano'],
    feels: ['fresco', 'floral', 'limpio'],
    topNotes: 'Notas acuosas, Frutos ligeros',
    heartNotes: 'Flores suaves',
    baseNotes: 'Almizcle blanco',
    duration: '3-4h',
    avoidTags: ['intenso', 'oud'],
    sweetness: 2,
    freshness: 5,
    intensity: 1,
    emotionalDesc: 'Un rocío de frescura etérea. Ideal para después del baño y mantener una sensación de limpieza pura.',
  },
  {
    id: 'amber-oud-gold-edition-ah',
    name: 'Amber Oud Gold Edition',
    brand: 'Al Haramain',
    gender: 'U',
    family: 'Ámbar Vainilla',
    occasions: ['diario', 'evento', 'evento'],
    feels: ['dulce', 'frutal'],
    topNotes: 'Bergamota, Notas verdes',
    heartNotes: 'Melón, Piña, Notas dulces, Ámbar',
    baseNotes: 'Vainilla, Almizcle, Notas amaderadas',
    duration: '12h+',
    avoidTags: ['suave', 'discreto'],
    sweetness: 5,
    freshness: 3,
    intensity: 5,
    emotionalDesc: 'La bestia dorada. Una explosión frutal de melón tan potente que llena habitaciones enteras con su dulzura.',
  },
  {
    id: 'coconut-passion-vs',
    name: 'Coconut Passion',
    brand: 'Victoria\'s Secret',
    gender: 'F',
    family: 'Floral Frutal Gourmand',
    occasions: ['verano', 'diario', 'cita'],
    feels: ['dulce', 'gourmand'],
    topNotes: 'Coco',
    heartNotes: 'Vainilla',
    baseNotes: 'Lirio de los valles, Manzanilla, Sábila',
    duration: '4h',
    avoidTags: ['especiado', 'oud'],
    sweetness: 5,
    freshness: 3,
    intensity: 2,
    emotionalDesc: 'Un paraíso tropical en la piel. Vainilla cremosa y coco que invitan a un descanso eterno bajo el sol.',
  },
  {
    id: 'eclaire-lattafa',
    name: 'Eclaire',
    brand: 'Lattafa',
    gender: 'F',
    family: 'Gourmand',
    occasions: ['cita', 'noche', 'invierno'],
    feels: ['dulce', 'gourmand'],
    topNotes: 'Caramelo, Leche, Azúcar',
    heartNotes: 'Flores blancas, Miel',
    baseNotes: 'Vainilla, Praliné, Almizcle',
    duration: '10h+',
    avoidTags: ['citrico', 'fresco'],
    sweetness: 5,
    freshness: 1,
    intensity: 4,
    emotionalDesc: 'Un postre de lujo. Caramelo sedoso y leche que crean una estela comestible y sumamente adictiva.',
  },
  {
    id: 'haya-lattafa',
    name: 'Haya',
    brand: 'Lattafa',
    gender: 'F',
    family: 'Floral Frutal Gourmand',
    occasions: ['diario', 'evento', 'verano'],
    feels: ['dulce', 'frutal', 'floral'],
    topNotes: 'Champaña rosada, Bayas rosadas, Naranja sanguina, Mandarina, Fresa',
    heartNotes: 'Gardenia, Jazmín, Orquídea de vainilla',
    baseNotes: 'Ámbar, Sándalo, Castaña',
    duration: '8h+',
    avoidTags: ['oud', 'amaderado-pesado'],
    sweetness: 4,
    freshness: 4,
    intensity: 4,
    emotionalDesc: 'Brindis de feminidad. Una champaña rosada con fresas que destila alegría y elegancia chispeante.',
  },
  {
    id: 'her-confession-lattafa',
    name: 'Her Confession',
    brand: 'Lattafa',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['cita', 'noche'],
    feels: ['floral', 'dulce', 'amaderado'],
    topNotes: 'Notas especiadas',
    heartNotes: 'Flores místicas',
    baseNotes: 'Vainilla, Ámbar',
    duration: '10h',
    avoidTags: ['citrico-ligero'],
    sweetness: 4,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Una confesión íntima y poderosa. Flores oscuras y vainilla para una mujer que guarda grandes secretos.',
  },
  {
    id: 'honor-and-glory-lattafa',
    name: 'Honor & Glory',
    brand: 'Lattafa',
    gender: 'U',
    family: 'Oriental Gourmand',
    occasions: ['diario', 'verano', 'evento'],
    feels: ['dulce', 'frutal'],
    topNotes: 'Piña Brulée',
    heartNotes: 'Cúrcuma, Canela, Pimienta negra, Benjuí',
    baseNotes: 'Vainilla, Cachemira, Sándalo, Musgo de roble',
    duration: '10h+',
    avoidTags: ['acuatico', 'floral-suave'],
    sweetness: 5,
    freshness: 3,
    intensity: 5,
    emotionalDesc: 'Piña asada con canela. Un aroma cálido, especiado y sumamente original que proyecta triunfo.',
  },
  {
    id: 'juiced-berry-mist',
    name: 'Juiced Berry',
    brand: 'Victoria\'s Secret',
    gender: 'F',
    family: 'Frutal',
    occasions: ['diario', 'verano'],
    feels: ['frutal', 'dulce', 'fresco'],
    topNotes: 'Frutos rojos, Frambuesa',
    heartNotes: 'Notas azucaradas',
    baseNotes: 'Almizcle suave',
    duration: '3-4h',
    avoidTags: ['oud', 'invierno'],
    sweetness: 4,
    freshness: 4,
    intensity: 2,
    emotionalDesc: 'Energía frutal jugosa. Como un sorbete de moras frescas, ligero y refrescante.',
  },
  {
    id: 'karpos-lattafa',
    name: 'Karpos',
    brand: 'Lattafa',
    gender: 'U',
    family: 'Aromática Frutal',
    occasions: ['diario', 'verano'],
    feels: ['frutal', 'fresco'],
    topNotes: 'Frutas tropicales',
    heartNotes: 'Notas verdes',
    baseNotes: 'Almizcle',
    duration: '8h',
    avoidTags: ['dulce-pesado'],
    sweetness: 3,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'Cosecha de frescura exótica. Una mezcla de frutas silvestres perfecta para mantenerse activo bajo el sol.',
  },
  {
    id: 'laventure-grapefruit-ah',
    name: 'L\'Aventure Grapefruit',
    brand: 'Al Haramain',
    gender: 'M',
    family: 'Cítrica Aromática',
    occasions: ['verano', 'trabajo', 'diario'],
    feels: ['fresco', 'citrico'],
    topNotes: 'Toronja, Bergamota',
    heartNotes: 'Ginger, Jazmín',
    baseNotes: 'Almizcle, Notas amaderadas',
    duration: '8h',
    avoidTags: ['dulce', 'invierno'],
    sweetness: 1,
    freshness: 5,
    intensity: 4,
    emotionalDesc: 'El despertar cítrico definitivo. Una toronja ultra realista y energizante que proyecta limpieza absoluta.',
  },
  {
    id: 'mallow-madness-lattafa',
    name: 'Mallow Madness',
    brand: 'Lattafa',
    gender: 'F',
    family: 'Gourmand',
    occasions: ['diario', 'cita'],
    feels: ['dulce', 'gourmand'],
    topNotes: 'Malvavisco, Azúcar',
    heartNotes: 'Vainilla cremosa',
    baseNotes: 'Almizcle suave',
    duration: '6-8h',
    avoidTags: ['citrico', 'especiado'],
    sweetness: 5,
    freshness: 2,
    intensity: 3,
    emotionalDesc: 'Una locura de azúcar. Esponjoso y dulce como una nube, perfecto para almas jóvenes y dulces.',
  },
  {
    id: 'mango-temptation-vs',
    name: 'Mango Temptation',
    brand: 'Victoria\'s Secret',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['verano', 'verano', 'diario'],
    feels: ['frutal', 'fresco', 'dulce'],
    topNotes: 'Mango',
    heartNotes: 'Hibisco',
    baseNotes: 'Manzanilla, Sábila',
    duration: '4h',
    avoidTags: ['invierno', 'pesado'],
    sweetness: 4,
    freshness: 4,
    intensity: 2,
    emotionalDesc: 'Tentación tropical. Mango jugoso y peonía que evocan atardeceres en la playa.',
  },
  {
    id: 'odyssey-candee-armaf',
    name: 'Odyssey Candee',
    brand: 'Armaf',
    gender: 'F',
    family: 'Floral Frutal Gourmand',
    occasions: ['diario', 'evento'],
    feels: ['dulce', 'frutal'],
    topNotes: 'Notas dulces, Frutas',
    heartNotes: 'Flores blancas',
    baseNotes: 'Vainilla, Almizcle',
    duration: '8h',
    avoidTags: ['oud', 'amargo'],
    sweetness: 5,
    freshness: 3,
    intensity: 4,
    emotionalDesc: 'Un viaje al mundo de los dulces. Golosinas y flores que crean una estela divertida y extremadamente adictiva.',
  },
  {
    id: 'oud-sublime-lattafa',
    name: 'Oud Sublime',
    brand: 'Lattafa',
    gender: 'U',
    family: 'Amaderada Aromática',
    occasions: ['noche', 'evento'],
    feels: ['oud', 'limpio', 'amaderado'],
    topNotes: 'Artemisia, Bergamota',
    heartNotes: 'Salvia, Oud',
    baseNotes: 'Cedro, Pachulí',
    duration: '10h+',
    avoidTags: ['dulce-pesado'],
    sweetness: 2,
    freshness: 3,
    intensity: 4,
    emotionalDesc: 'La sublimación del oud. Un aroma maderoso pero sorprendentemente aireado y refinado.',
  },
  {
    id: 'sublime-lattafa-unisex',
    name: 'Sublime',
    brand: 'Lattafa',
    gender: 'U',
    family: 'Floral Frutal',
    occasions: ['diario', 'trabajo', 'evento'],
    feels: ['fresco', 'floral', 'frutal'],
    topNotes: 'Manzana, Lichi, Rosa',
    heartNotes: 'Ciruela, Jazmín',
    baseNotes: 'Vainilla, Musgo, Pachulí',
    duration: '10h',
    avoidTags: ['oud', 'pesado'],
    sweetness: 3,
    freshness: 4,
    intensity: 4,
    emotionalDesc: 'Belleza en estado puro. Un equilibrio magistral de lichi y rosas que se siente lujoso y vibrante.',
  },
  {
    id: 'vanilla-lace-mist',
    name: 'Vanilla Lace',
    brand: 'Victoria\'s Secret',
    gender: 'F',
    family: 'Ámbar Vainilla',
    occasions: ['diario', 'noche'],
    feels: ['dulce', 'gourmand'],
    topNotes: 'Vainilla',
    heartNotes: 'Orquídea',
    baseNotes: 'Almizcle',
    duration: '4h',
    avoidTags: ['citrico', 'fresco'],
    sweetness: 5,
    freshness: 1,
    intensity: 2,
    emotionalDesc: 'Vainilla clásica y reconfortante. Un aroma cálido que se siente como una segunda piel acogedora.',
  },
  {
    id: 'yara-candy-lattafa',
    name: 'Yara Candy',
    brand: 'Lattafa',
    gender: 'F',
    family: 'Frutal Gourmand',
    occasions: ['diario', 'cita', 'evento'],
    feels: ['dulce', 'frutal', 'gourmand'],
    topNotes: 'Caramelos, Frutas rojas',
    heartNotes: 'Flor del naranjo, Vainilla',
    baseNotes: 'Almizcle, Ámbar',
    duration: '8h+',
    avoidTags: ['serio', 'oud'],
    sweetness: 5,
    freshness: 3,
    intensity: 4,
    emotionalDesc: 'La versión más dulce de Yara. Un estallido de caramelos y gomitas frutales para una mujer vibrante.',
  },
  {
    id: 'yum-yum-lattafa',
    name: 'Yum Yum',
    brand: 'Lattafa',
    gender: 'U',
    family: 'Oriental Gourmand',
    occasions: ['cita', 'noche'],
    feels: ['dulce', 'gourmand'],
    topNotes: 'Pistacho, Helado',
    heartNotes: 'Algodón de azúcar, Malvavisco',
    baseNotes: 'Sándalo, Vainilla',
    duration: '10h',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 5,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Un banquete de pistacho y helado. Cremoso, dulce y sumamente "yum", imposible de ignorar.',
  },
  {
    id: 'yara-lattafa',
    name: 'Yara (Rosada)',
    brand: 'Lattafa',
    gender: 'F',
    family: 'Ámbar Vainilla',
    occasions: ['diario', 'cita', 'trabajo'],
    feels: ['dulce', 'gourmand', 'floral'],
    topNotes: 'Orquídea, Heliotropo, Mandarina',
    heartNotes: 'Gourmand, Frutas tropicales',
    baseNotes: 'Vainilla, Almizcle, Sándalo',
    duration: '6-8h',
    avoidTags: ['oud', 'citrico'],
    sweetness: 5,
    freshness: 3,
    intensity: 3,
    emotionalDesc: 'Un batido de fresa celestial derramado sobre orquídeas blancas. Esponjoso, inocente, ultra-femenino y súper envidiado.',
  },
  {
    id: 'yara-moi',
    name: 'Yara Moi (Blanca)',
    brand: 'Lattafa',
    gender: 'F',
    family: 'Ámbar Gourmand',
    occasions: ['diario', 'cita', 'trabajo'],
    feels: ['dulce', 'especiado', 'gourmand'],
    topNotes: 'Caramelo, Durazno',
    heartNotes: 'Pachulí, Ámbar',
    baseNotes: 'Sándalo',
    duration: '8h',
    avoidTags: ['oud', 'fresco', 'citrico'],
    sweetness: 4,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Elegancia tostada. Una rebanada de durazno caramelizado navegando sobre maderas lujosas.',
  },
  {
    id: 'yara-tous',
    name: 'Yara Tous (Amarillo)',
    brand: 'Lattafa',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['verano', 'diario', 'trabajo'],
    feels: ['frutal', 'dulce', 'fresco'],
    topNotes: 'Mango, Maracuyá',
    heartNotes: 'Jazmín, Flor de Heliotropo',
    baseNotes: 'Vainilla, Ámbar',
    duration: '6-8h',
    avoidTags: ['oud'],
    sweetness: 4,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'Vacaciones de verano eternas encapsuladas en un mango soleado del Medio Oriente. Vibrante y adictivo.',
  },
  {
    id: 'carioca-crush-sol-de-janeiro',
    name: 'Carioca Crush',
    brand: 'Sol de Janeiro',
    gender: 'F',
    family: 'Frutal',
    occasions: ['diario', 'verano'],
    feels: ['frutal', 'fresco', 'dulce'],
    topNotes: 'Mandarina helada',
    heartNotes: 'Orquídea salvaje',
    baseNotes: 'Pistacho tostado',
    duration: '3-4h',
    avoidTags: ['oud', 'amaderado'],
    sweetness: 4,
    freshness: 5,
    intensity: 2,
    emotionalDesc: 'Tu pasaporte sin escalas a las playas vibrantes de Río de Janeiro. Citas al sol y mucha frescura frutal en tu piel.',
  },
  {
    id: 'coconut-passion-vs',
    name: 'Coconut Passion',
    brand: 'Victoria\'s Secret',
    gender: 'F',
    family: 'Floral Frutal Gourmand',
    occasions: ['diario', 'verano'],
    feels: ['dulce', 'gourmand', 'frutal'],
    topNotes: 'Coco',
    heartNotes: 'Vainilla',
    baseNotes: 'Lirio de los valles',
    duration: '3-4h',
    avoidTags: ['oud', 'especiado'],
    sweetness: 5,
    freshness: 3,
    intensity: 2,
    emotionalDesc: 'La isla prometida bañada en leche de coco. Un romance playero eterno e inconfundible de Victoria\'s Secret.',
  },
  {
    id: 'pure-seduction-vs',
    name: 'Pure Seduction',
    brand: 'Victoria\'s Secret',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'cita'],
    feels: ['frutal', 'dulce', 'floral'],
    topNotes: 'Ciruela roja',
    heartNotes: 'Fresia',
    baseNotes: 'Notas dulces',
    duration: '3-4h',
    avoidTags: ['oud', 'especiado'],
    sweetness: 4,
    freshness: 4,
    intensity: 2,
    emotionalDesc: 'Jugosa, coqueta e impulsiva. Un susurro frutal que roza la picardía para conquistar en tu rutina.',
  },
];
