import type { Perfume } from '../types';

export const mujeresNuevas: Perfume[] = [
  {
    id: '212-nyc',
    name: '212 NYC',
    brand: 'Carolina Herrera',
    gender: 'F',
    family: 'Almizcle Floral Amaderado',
    occasions: ['diario', 'trabajo', 'verano'],
    feels: ['fresco', 'citrico', 'floral'],
    topNotes: 'Azahar, Mandarina, Flor de cactus, Bergamota',
    heartNotes: 'Camelia Blanca, Azucena, Gardenia, Fresia, Jazmín',
    baseNotes: 'Sándalo, Almizcle Blanc',
    duration: '6-8h',
    avoidTags: ['dulce-intenso', 'intenso', 'oud'],
    sweetness: 2,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'Una brisa urbana de pura elegancia. Para la mujer moderna de ciudad que pisa fuerte desde temprano.',
  },
  {
    id: '212-sexy',
    name: '212 Sexy',
    brand: 'Carolina Herrera',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['noche', 'cita', 'invierno'],
    feels: ['dulce', 'especiado', 'amaderado'],
    topNotes: 'Pimienta rosa, Mandarina, Bergamota',
    heartNotes: 'Algodón de azúcar, Gardenia, Pelargonio',
    baseNotes: 'Vainilla, Almizcle, Sándalo, Caramelo',
    duration: '8-10h',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 4,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Adictivo, dulce y travieso. Como un secreto susurrado al oído en una noche vibrante de ciudad.',
  },
  {
    id: '212-vip',
    name: '212 VIP',
    brand: 'Carolina Herrera',
    gender: 'F',
    family: 'Ámbar Vainilla',
    occasions: ['noche', 'evento'],
    feels: ['dulce', 'gourmand'],
    topNotes: 'Ron, Maracuyá',
    heartNotes: 'Gardenia, Almizcle',
    baseNotes: 'Vainilla, Haba Tonka',
    duration: '10h+',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 5,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'La lista de invitados soñada. Un shot de oro líquido que grita diversión y lujo nocturno.',
  },
  {
    id: '212-vip-rose',
    name: '212 VIP Rosé',
    brand: 'Carolina Herrera',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'cita', 'evento'],
    feels: ['frutal', 'floral', 'fresco'],
    topNotes: 'Champán, Notas afrutadas',
    heartNotes: 'Flor de duraznero',
    baseNotes: 'Almizcle Blanco, Notas amaderadas',
    duration: '6-8h',
    avoidTags: ['intenso', 'oud'],
    sweetness: 3,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'Espumoso, chic y vibrante. La sonrisa más brillante de la mejor fiesta en los Hamptons.',
  },
  {
    id: '212-vip-wild-party',
    name: '212 VIP Wild Party',
    brand: 'Carolina Herrera',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['noche', 'evento'],
    feels: ['frutal', 'dulce'],
    topNotes: 'Piña, Pomelo',
    heartNotes: 'Flor de Azahar, Orquídea, Rosa',
    baseNotes: 'Almizcle, Notas Amaderadas',
    duration: '8h+',
    avoidTags: ['fresco'],
    sweetness: 4,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Un safari urbano lleno de excesos tropicales de las mejores noches. Salvaje y opulento.',
  },
  {
    id: '273-beverly-hills',
    name: '273',
    brand: 'Fred Hayman',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['evento', 'noche'],
    feels: ['floral', 'amaderado'],
    topNotes: 'Tuberosa, Durazno, Ciruela, Jazmín',
    heartNotes: 'Albaricoque, Ylang-Ylang, Rosa',
    baseNotes: 'Ámbar, Sándalo, Especias',
    duration: '10h+',
    avoidTags: ['fresco', 'citrico', 'gourmand'],
    sweetness: 3,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'El glamour intemporal de Rodeo Drive. Potente, narcótico y destinado a robar las miradas de toda gala.',
  },
  {
    id: '360-perry-ellis',
    name: '360°',
    brand: 'Perry Ellis',
    gender: 'F',
    family: 'Floral',
    occasions: ['diario', 'trabajo', 'verano'],
    feels: ['floral', 'fresco'],
    topNotes: 'Melón, Lirio de los valles, Osmanto',
    heartNotes: 'Lirio de agua, Salvia, Lavanda',
    baseNotes: 'Almizcle, Vetiver, Ámbar',
    duration: '6-8h',
    avoidTags: ['dulce-intenso', 'oud', 'gourmand'],
    sweetness: 2,
    freshness: 5,
    intensity: 3,
    emotionalDesc: 'Una frescura cristalina que envuelve en 360 grados. El rocío de la mañana atrapado en una burbuja.',
  },
  {
    id: 'ange-ou-demon',
    name: 'Ange ou Démon',
    brand: 'Givenchy',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['noche', 'cita', 'invierno'],
    feels: ['dulce', 'especiado'],
    topNotes: 'Azafrán, Tomillo, Mandarina',
    heartNotes: 'Azucena, Ylang-Ylang, Orquídea',
    baseNotes: 'Vainilla, Haba Tonka, Palisandro',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 4,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'El juego fatal de la dualidad. Oscura, misteriosa y profundamente magnética. Un enigma que nadie quiere resolver.',
  },
  {
    id: 'ari-ariana-grande',
    name: 'Ari',
    brand: 'Ariana Grande',
    gender: 'F',
    family: 'Floral Frutal Gourmand',
    occasions: ['diario', 'cita'],
    feels: ['dulce', 'frutal', 'gourmand'],
    topNotes: 'Frambuesa, Pera, Toronja',
    heartNotes: 'Orquídea de vainilla, Rosa, Lirio',
    baseNotes: 'Malvavisco, Almizcle, Maderas rubias',
    duration: '6h',
    avoidTags: ['amaderado', 'oud', 'intenso'],
    sweetness: 5,
    freshness: 3,
    intensity: 3,
    emotionalDesc: 'Divertida, femenina y súper tentadora. Suave como un malvavisco bajo un atardecer rosado.',
  },
  {
    id: 'bff-kim-kardashian',
    name: 'BFF',
    brand: 'Kim Kardashian',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'verano'],
    feels: ['dulce', 'frutal'],
    topNotes: 'Frutos rojos',
    heartNotes: 'Flores suaves',
    baseNotes: 'Almizcle, Vainilla',
    duration: '4-6h',
    avoidTags: ['intenso', 'oud', 'amaderado'],
    sweetness: 4,
    freshness: 3,
    intensity: 2,
    emotionalDesc: 'La esencia de una amistad inolvidable. Frutal, fácil de llevar y llena de energía.',
  },
  {
    id: 'bright-crystal',
    name: 'Bright Crystal',
    brand: 'Versace',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'verano', 'trabajo'],
    feels: ['fresco', 'floral'],
    topNotes: 'Yuzu, Granada, Hielo',
    heartNotes: 'Peonía, Loto, Magnolia',
    baseNotes: 'Almizcle, Caoba, Ámbar',
    duration: '6h',
    avoidTags: ['dulce-intenso', 'gourmand', 'oud'],
    sweetness: 2,
    freshness: 5,
    intensity: 3,
    emotionalDesc: 'Un diamante tallado en hielo. Fresca, cristalina y peligrosamente adictiva en una tarde de sol brumoso.',
  },
  {
    id: 'burberry-her',
    name: 'Her',
    brand: 'Burberry',
    gender: 'F',
    family: 'Floral Frutal Gourmand',
    occasions: ['diario', 'cita', 'verano'],
    feels: ['frutal', 'dulce', 'gourmand'],
    topNotes: 'Fresa, Frambuesa, Mora',
    heartNotes: 'Violeta, Jazmín',
    baseNotes: 'Amizcle, Vainilla, Cachemira, Notas amaderadas',
    duration: '8h',
    avoidTags: ['especiado', 'oud'],
    sweetness: 4,
    freshness: 3,
    intensity: 4,
    emotionalDesc: 'Una sobredosis de fresas con crema en la calle Oxford de Londres. Un halo vibrante y excepcionalmente chic.',
  },
  {
    id: 'burberry-her-elixir',
    name: 'Her Elixir de Parfum',
    brand: 'Burberry',
    gender: 'F',
    family: 'Fruity Gourmand',
    occasions: ['cita', 'noche', 'invierno'],
    feels: ['dulce', 'gourmand'],
    topNotes: 'Fresa, Mora',
    heartNotes: 'Jazmín',
    baseNotes: 'Vainilla, Ámbar, Sándalo',
    duration: '10h+',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 5,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'La cereza de coronación de las golosinas británicas. Opulenta, densa, un batido lácteo y sofisticado.',
  },
  {
    id: 'burberry-london-her',
    name: 'Burberry London',
    brand: 'Burberry',
    gender: 'F',
    family: 'Floral',
    occasions: ['trabajo', 'diario', 'invierno'],
    feels: ['floral', 'fresco'],
    topNotes: 'Madreselva, Tangerina, Rosa',
    heartNotes: 'Jazmín, Flor de tiaré, Peonía, Clementina',
    baseNotes: 'Almizcle, Sándalo, Pachulí',
    duration: '6-8h',
    avoidTags: ['gourmand', 'dulce-intenso', 'oud'],
    sweetness: 2,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'La elegancia de una gabardina tradicional caminando bajo una fresca llovizna londinense de flores.',
  },
  {
    id: 'can-can',
    name: 'Can Can',
    brand: 'Paris Hilton',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'noche', 'cita'],
    feels: ['dulce', 'frutal'],
    topNotes: 'Nectarina, Grosellas negras, Clementina',
    heartNotes: 'Orquídea silvestre, Flor de azahar',
    baseNotes: 'Ámbar, Almizcle, Notas amaderadas',
    duration: '6-8h',
    avoidTags: ['oud', 'fresco', 'citrico'],
    sweetness: 4,
    freshness: 3,
    intensity: 3,
    emotionalDesc: 'La energía chispeante de los cabarets en París. Frutas dulces bailando un torbellino sensual.',
  },
  {
    id: 'chance-chanel',
    name: 'Chance',
    brand: 'Chanel',
    gender: 'F',
    family: 'Chipre Floral',
    occasions: ['trabajo', 'diario', 'cita'],
    feels: ['floral', 'especiado', 'fresco'],
    topNotes: 'Pimienta rosa, Limón, Piña',
    heartNotes: 'Jacinto, Jazmín, Iris',
    baseNotes: 'Pachulí, Almizcle, Vetiver, Vainilla',
    duration: '8h+',
    avoidTags: ['gourmand', 'polvo', 'oud'],
    sweetness: 2,
    freshness: 4,
    intensity: 4,
    emotionalDesc: 'Gira la ruleta y atrévete a todo. Un velo impredecible y refinado de pimienta y pachulí que envuelve de magnetismo.',
  },
  {
    id: 'chanel-no-5',
    name: 'Chanel N°5',
    brand: 'Chanel',
    gender: 'F',
    family: 'Floral Aldehídico',
    occasions: ['evento', 'noche', 'trabajo'],
    feels: ['floral', 'amaderado'],
    topNotes: 'Aldehídos, Ylang-Ylang, Neroli, Limón',
    heartNotes: 'Iris, Jazmín, Rosa, Lirio de los valles',
    baseNotes: 'Sándalo, Vainilla, Musgo de roble, Vetiver',
    duration: '10h+',
    avoidTags: ['dulce', 'gourmand', 'fresco', 'polvo'],
    sweetness: 2,
    freshness: 3,
    intensity: 5,
    emotionalDesc: 'La leyenda absoluta de la perfumería. Un ramo abstracto que transforma a cualquier mujer en un ícono atemporal.',
  },
  {
    id: 'cloud',
    name: 'Cloud',
    brand: 'Ariana Grande',
    gender: 'F',
    family: 'Floral Frutal Gourmand',
    occasions: ['diario', 'trabajo', 'cita'],
    feels: ['dulce', 'gourmand'],
    topNotes: 'Lavanda, Pera, Bergamota',
    heartNotes: 'Crema batida, Praliné, Coco, Orquídea',
    baseNotes: 'Almizcle, Notas amaderadas',
    duration: '8h',
    avoidTags: ['citrico', 'oud'],
    sweetness: 5,
    freshness: 2,
    intensity: 3,
    emotionalDesc: 'Dormir entre nubes esponjosas y azúcar. Una textura aérea e inconfundible que enamora desde el primer segundo.',
  },
  {
    id: 'coco-mademoiselle',
    name: 'Coco Mademoiselle',
    brand: 'Chanel',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['trabajo', 'evento', 'cita'],
    feels: ['floral', 'fresco', 'amaderado'],
    topNotes: 'Naranja, Mandarina, Bergamota',
    heartNotes: 'Rosa turca, Jazmín, Mimosa',
    baseNotes: 'Pachulí, Almizcle blanco, Vainilla, Vetiver',
    duration: '10h+',
    avoidTags: ['gourmand', 'dulce-intenso'],
    sweetness: 3,
    freshness: 4,
    intensity: 5,
    emotionalDesc: 'La rebeldía envuelta en la máxima elegancia francesa. Impecable, incisiva, y poderosamente atractiva.',
  },
  {
    id: 'coco-noir',
    name: 'Coco Noir',
    brand: 'Chanel',
    gender: 'F',
    family: 'Ámbar Amaderado',
    occasions: ['noche', 'evento', 'invierno'],
    feels: ['especiado', 'amaderado'],
    topNotes: 'Toronja, Bergamota, Naranja',
    heartNotes: 'Rosa, Geranio, Narciso',
    baseNotes: 'Pachulí, Sándalo, Incienso, Haba tonka',
    duration: '12h',
    avoidTags: ['fresco', 'citrico', 'gourmand'],
    sweetness: 3,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'El lujo del negro veneciano revelado por la noche. Sensual, mística y envuelta en un aura misteriosa insuperable.',
  },
  {
    id: 'donna-valentino',
    name: 'Donna',
    brand: 'Valentino',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['cita', 'evento', 'trabajo'],
    feels: ['floral', 'dulce', 'amaderado'],
    topNotes: 'Bergamota',
    heartNotes: 'Iris, Rosa de Bulgaria',
    baseNotes: 'Vainilla, Cuero, Pachulí',
    duration: '8h+',
    avoidTags: ['fresco', 'citrico', 'polvo', 'cuero'],
    sweetness: 3,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Una aristocracia moderna con rebeldía. La dulzura de la rosa con los toques atalcados del cuero fino italiano.',
  },
  {
    id: 'eau-franchie',
    name: 'Eau Fraîche (Lacoste insp)',
    brand: 'Genérica',
    gender: 'F',
    family: 'Cítrico Aromático',
    occasions: ['diario', 'verano'],
    feels: ['fresco', 'citrico'],
    topNotes: 'Limón, Bergamota',
    heartNotes: 'Flores blancas, Verdes',
    baseNotes: 'Almizcle, Maderas ligeras',
    duration: '4-6h',
    avoidTags: ['dulce-intenso', 'gourmand', 'oud'],
    sweetness: 1,
    freshness: 5,
    intensity: 2,
    emotionalDesc: 'Claridad pura envasada. Una ráfaga fresca al salir de la ducha que empodera cada inicio de día.',
  },
  {
    id: 'eden-juicy-apple',
    name: 'Eden Juicy Apple | 01',
    brand: 'Kayali',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'verano', 'cita'],
    feels: ['frutal', 'dulce', 'fresco'],
    topNotes: 'Manzana roja, Lichi, Pomelo',
    heartNotes: 'Bayas silvestres, Rosa, Jazmín',
    baseNotes: 'Almizcle, Flor de vainilla, Musgo',
    duration: '6h',
    avoidTags: ['intenso', 'oud', 'especiado'],
    sweetness: 4,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'El pecado original hecho jugo de manzanas frescas y chispeantes. Jugosa e irresistible, provoca morderla.',
  },
  {
    id: 'elixir-shakira',
    name: 'Elixir',
    brand: 'Shakira',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['noche', 'cita', 'invierno'],
    feels: ['especiado', 'dulce', 'floral'],
    topNotes: 'Pimienta negra, Flor de azahar',
    heartNotes: 'Durazno, Fresia, Peonía',
    baseNotes: 'Ámbar, Azúcar moreno, Almizcle',
    duration: '6-8h',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 4,
    freshness: 2,
    intensity: 3,
    emotionalDesc: 'Un hechizo cálido y exótico. Como el calor sensual de una danza del medio oriente.',
  },
  {
    id: 'funny-moschino',
    name: 'Funny!',
    brand: 'Moschino',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'verano'],
    feels: ['citrico', 'fresco', 'frutal'],
    topNotes: 'Naranja amarga, Grosella roja, Pimienta rosa',
    heartNotes: 'Té verde, Peonía, Jazmín, Violeta',
    baseNotes: 'Cedro, Almizcle, Ámbar',
    duration: '5-7h',
    avoidTags: ['gourmand', 'intenso', 'oud', 'polvo'],
    sweetness: 2,
    freshness: 5,
    intensity: 2,
    emotionalDesc: 'Optimismo en su estado más burbujeante. Un guiño coqueto y cítrico para la mujer que no pierde la sonrisa.',
  },
  {
    id: 'gaultier-divine',
    name: 'Gaultier Divine',
    brand: 'Jean Paul Gaultier',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['noche', 'evento', 'cita'],
    feels: ['floral', 'dulce', 'fresco'],
    topNotes: 'Calipsone, Bayas rojas, Bergamota',
    heartNotes: 'Azucena, Jazmín, Ylang-Ylang',
    baseNotes: 'Merengue, Almizcle, Pachulí',
    duration: '8h+',
    avoidTags: ['oud', 'citrico'],
    sweetness: 4,
    freshness: 3,
    intensity: 4,
    emotionalDesc: 'Una diosa marina saliendo entre espumas dulces de merengue. Majestuosa, moderna e infinitamente femenina.',
  },
  {
    id: 'golden-rush',
    name: 'Golden Rush',
    brand: 'Paris Hilton',
    gender: 'F',
    family: 'Floral Frutal Gourmand',
    occasions: ['noche', 'evento'],
    feels: ['dulce', 'floral', 'gourmand'],
    topNotes: 'Nectarina, Bergamota, Manzana',
    heartNotes: 'Orquídea, Violeta, Rosa',
    baseNotes: 'Praliné, Almizcle, Cachemira',
    duration: '6-8h',
    avoidTags: ['fresco', 'citrico', 'polvo'],
    sweetness: 5,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'El lujo destellante envuelto en oro líquido. Irresistible y sumamente seductora bajo las luces neon.',
  },
  {
    id: 'in-2-u-ck',
    name: 'In2U',
    brand: 'Calvin Klein',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['diario', 'verano', 'trabajo'],
    feels: ['citrico', 'fresco', 'dulce'],
    topNotes: 'Hojas del grosellero rojo, Toronja, Bergamota',
    heartNotes: 'Orquídea, Cactus',
    baseNotes: 'Vainilla, Cedro rojo, Ámbar',
    duration: '5-7h',
    avoidTags: ['intenso', 'gourmand', 'oud'],
    sweetness: 3,
    freshness: 4,
    intensity: 2,
    emotionalDesc: 'Urbana, libre y despampanante. Un destello energizante de cítricos fusionado con azúcar de vainilla vibrante.',
  },
  {
    id: 'la-vie-est-belle',
    name: 'La Vie Est Belle',
    brand: 'Lancôme',
    gender: 'F',
    family: 'Floral Frutal Gourmand',
    occasions: ['cita', 'noche', 'evento'],
    feels: ['dulce', 'floral', 'gourmand'],
    topNotes: 'Grosellas negras, Pera',
    heartNotes: 'Iris, Jazmín, Flor de azahar',
    baseNotes: 'Praliné, Vainilla, Pachulí, Haba tonka',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico', 'polvo'],
    sweetness: 5,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'La sonrisa de la felicidad absoluta. Un abrazo poderoso de praliné que empodera y se convierte en inolvidable.',
  },
  {
    id: 'good-girl-blush-ch',
    name: 'Good Girl Blush',
    brand: 'Carolina Herrera',
    gender: 'F',
    family: 'Chipre Floral',
    occasions: ['diario', 'evento', 'cita'],
    feels: ['floral', 'atalcado', 'dulce'],
    topNotes: 'Bergamota, Almendra amarga',
    heartNotes: 'Peonía, Ylang-Ylang',
    baseNotes: 'Vainilla, Cumarina',
    duration: '8-10h',
    avoidTags: ['acuatico', 'oud'],
    sweetness: 4,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'La dualidad más romántica. Una explosión floral empolvada con la sensualidad característica de Good Girl.',
  },
  {
    id: 'guess-pink-female',
    name: 'Guess for Women',
    brand: 'Guess',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'verano', 'trabajo'],
    feels: ['fresco', 'frutal', 'floral'],
    topNotes: 'Manzana verde, Fresa, Bergamota, Tangerina',
    heartNotes: 'Peonía, Magnolia, Fresia, Bayas rojas, Jazmín, Lirio de los valles',
    baseNotes: 'Almizcle, Cedro, Ámbar, Musgo de roble',
    duration: '6-8h',
    avoidTags: ['dulce-pesado'],
    sweetness: 2,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'Fresco, sexy y juvenil. Una mezcla chispeante de manzana y fresa perfecta para brillar bajo el sol.',
  },
  {
    id: 'meow-katy-perry-female',
    name: 'Meow',
    brand: 'Katy Perry',
    gender: 'F',
    family: 'Floral Frutal Gourmand',
    occasions: ['diario', 'noche'],
    feels: ['dulce', 'gourmand'],
    topNotes: 'Pera, Tangerina, Gardenia, Jazmín',
    heartNotes: 'Madreselva, Flor del naranjo, Lirio de los valles',
    baseNotes: 'Vainilla, Ámbar, Almizcle, Sándalo',
    duration: '6h',
    avoidTags: ['oud', 'amargo'],
    sweetness: 5,
    freshness: 2,
    intensity: 3,
    emotionalDesc: 'Un ronroneo de vainilla. Dulzura cremosa y adictiva que se siente como un abrazo suave.',
  },
  {
    id: 'miss-dior-edp-female',
    name: 'Miss Dior Eau de Parfum',
    brand: 'Dior',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['evento', 'cita', 'trabajo'],
    feels: ['floral', 'dulce', 'fresco'],
    topNotes: 'Iris, Peonía, Lirio de los valles',
    heartNotes: 'Albaricoque, Rosa, Durazno',
    baseNotes: 'Vainilla, Haba Tonka, Almizcle, Benjuí, Sándalo',
    duration: '8-10h',
    avoidTags: ['acuatico-marino'],
    sweetness: 3,
    freshness: 3,
    intensity: 4,
    emotionalDesc: 'Un "Millefiori" olfativo. Rosas vibrantes y flores frescas para una mujer elegante y llena de amor.',
  },
  {
    id: 'moon-sparkle-escada-female',
    name: 'Moon Sparkle',
    brand: 'Escada',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['verano', 'diario', 'noche'],
    feels: ['frutal', 'dulce', 'fresco'],
    topNotes: 'Fresa, Grosella negra, Frutos rojos, Cítricos',
    heartNotes: 'Gisante dulce, Fresia, Jazmín, Rosa',
    baseNotes: 'Frambuesa, Almizcle, Sándalo, Ámbar',
    duration: '6-8h',
    avoidTags: ['oud', 'especiado-pesado'],
    sweetness: 4,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'Noches mágicas de verano. Un cóctel de frutos rojos bajo la luz de la luna, vibrante y seductor.',
  },
  {
    id: 'omnia-crystalline-bvlgari',
    name: 'Omnia Crystalline',
    brand: 'Bvlgari',
    gender: 'F',
    family: 'Floral Acuática',
    occasions: ['trabajo', 'diario', 'verano'],
    feels: ['fresco', 'acuatico', 'limpio'],
    topNotes: 'Bambú, Pera',
    heartNotes: 'Flor de Loto, Té, Casia',
    baseNotes: 'Almizcle, Madera de Guayaco, Musgo de roble',
    duration: '6-8h',
    avoidTags: ['dulce-gourmand', 'oriental'],
    sweetness: 1,
    freshness: 5,
    intensity: 2,
    emotionalDesc: 'La claridad del cristal. Pera y loto que crean un aura de pureza, zen y frescura inigualable.',
  },
  {
    id: 'pineapple-dg-female',
    name: 'Pineapple',
    brand: 'Dolce & Gabbana',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['verano', 'diario'],
    feels: ['frutal', 'fresco', 'citrico'],
    topNotes: 'Piña, Mandarina siciliana',
    heartNotes: 'Jazmín sambac',
    baseNotes: 'Vainilla absoluta, Ámbar gris, Orquídea, Almizcle',
    duration: '8h',
    avoidTags: ['oud', 'invierno'],
    sweetness: 3,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'Un rayo de sol siciliano. Piña jugosa y exótica que celebra la alegría de vivir mediterránea.',
  },
  {
    id: 'sorbetto-rosso-escada-female',
    name: 'Sorbetto Rosso',
    brand: 'Escada',
    gender: 'F',
    family: 'Aromática Frutal',
    occasions: ['verano', 'verano', 'diario'],
    feels: ['frutal', 'fresco', 'acuatico'],
    topNotes: 'Sandía, Pera, Calone',
    heartNotes: 'Sal de mar, Fresa, Flor de tiaré, Jazmín, Rosa',
    baseNotes: 'Praliné, Almizcle, Ámbar',
    duration: '6h',
    avoidTags: ['invierno', 'pesado'],
    sweetness: 4,
    freshness: 5,
    intensity: 2,
    emotionalDesc: 'Un sorbete de sandía frío frente al mar. La frescura máxima del verano mediterráneo.',
  },
  {
    id: 'thank-u-next-ag-female',
    name: 'Thank U, Next',
    brand: 'Ariana Grande',
    gender: 'F',
    family: 'Floral Frutal Gourmand',
    occasions: ['diario', 'evento'],
    feels: ['dulce', 'frutal', 'gourmand'],
    topNotes: 'Frambuesa, Pera blanca',
    heartNotes: 'Coco, Rosa rosada',
    baseNotes: 'Macarrones dulces, Almizcle',
    duration: '8h',
    avoidTags: ['oud', 'maduro-pesado'],
    sweetness: 5,
    freshness: 3,
    intensity: 4,
    emotionalDesc: 'Un nuevo comienzo dulce. Coco y macarrones rosas para una actitud empoderada y divertida.',
  },
  {
    id: 'toy-2-bubblegum-moschino',
    name: 'Toy 2 Bubble Gum',
    brand: 'Moschino',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'evento', 'evento'],
    feels: ['dulce', 'frutal', 'floral'],
    topNotes: 'Frutos confitados, Limón de Italia',
    heartNotes: 'Goma de mascar, Rosa de Bulgaria, Arándano, Durazno',
    baseNotes: 'Cedro, Almizcle, Ambroxan',
    duration: '6-8h',
    avoidTags: ['serio', 'formal'],
    sweetness: 5,
    freshness: 3,
    intensity: 3,
    emotionalDesc: 'Puro chicle rosa. Una explosión divertida y pop que no teme ser el centro de atención.',
  },
  {
    id: 'toy-2-pearls-moschino',
    name: 'Toy 2 Pearls',
    brand: 'Moschino',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['verano', 'diario', 'evento'],
    feels: ['fresco', 'citrico', 'floral'],
    topNotes: 'Limón de Italia, Orégano, Sorbete',
    heartNotes: 'Arena, Fresia, Jazmín',
    baseNotes: 'Almizcle, Ciprés, Vetiver',
    duration: '8h',
    avoidTags: ['dulce-pesado'],
    sweetness: 1,
    freshness: 5,
    intensity: 4,
    emotionalDesc: 'Un viaje al fondo del mar. Frescura cítrica y notas saladas que evocan sirenas modernas y elegantes.',
  },
  {
    id: 'very-good-girl-glam-ch',
    name: 'Very Good Girl Glam',
    brand: 'Carolina Herrera',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['noche', 'evento', 'cita'],
    feels: ['dulce', 'frutal', 'floral'],
    topNotes: 'Cereza ácida, Almendra amarga',
    heartNotes: 'Rosa, Azucena',
    baseNotes: 'Vainilla de Borbón, Vetiver',
    duration: '10h+',
    avoidTags: ['citrico-ligero'],
    sweetness: 4,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'La máxima expresión del glamour. Cereza brillante y vainilla para una mujer audaz y deslumbrante.',
  },
  {
    id: 'lady-million-royal',
    name: 'Lady Million Royal',
    brand: 'Paco Rabanne',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['noche', 'evento', 'cita'],
    feels: ['dulce', 'frutal', 'floral'],
    topNotes: 'Granada, Mandarina',
    heartNotes: 'Flores blancas, Tuberosa, Jazmín',
    baseNotes: 'Cashmeran, Notas amaderadas',
    duration: '8h+',
    avoidTags: ['fresco', 'citrico', 'oud'],
    sweetness: 4,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'La reina impenitente toma el trono. Opulencia jugosa diseñada para gobernar las pasarelas del placer.',
  },
  {
    id: 'light-blue-dg',
    name: 'Light Blue',
    brand: 'Dolce & Gabbana',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'verano', 'trabajo'],
    feels: ['citrico', 'fresco', 'amaderado'],
    topNotes: 'Limón siciliano, Manzana, Cedro',
    heartNotes: 'Bambú, Jazmín, Rosa blanca',
    baseNotes: 'Almizcle, Cedro, Ámbar',
    duration: '6-8h',
    avoidTags: ['dulce-intenso', 'gourmand', 'oud'],
    sweetness: 2,
    freshness: 5,
    intensity: 3,
    emotionalDesc: 'El sol glorioso de la costa mediterránea sobre la piel. Refrescante, ligera e inevitablemente icónica.',
  },
  {
    id: 'love-in-white-creed',
    name: 'Love in White',
    brand: 'Creed',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['evento', 'trabajo', 'cita'],
    feels: ['floral', 'fresco'],
    topNotes: 'Cáscara de Naranja',
    heartNotes: 'Arroz, Iris, Magnolia, Narciso, Rosa',
    baseNotes: 'Sándalo, Vainilla, Ámbar gris',
    duration: '10h+',
    avoidTags: ['gourmand', 'oud', 'dulce-intenso', 'polvo'],
    sweetness: 2,
    freshness: 4,
    intensity: 4,
    emotionalDesc: 'Pura aristocracia. Pétalos sumergidos en crema fresca y elegante que huele a triunfo sin hacer esfuerzo.',
  },
];
