import type { Perfume } from '../types';

export const hombresNuevos: Perfume[] = [
  {
    id: 'sauvage-edp-dior',
    name: 'Sauvage EDT/EDP',
    brand: 'Dior',
    gender: 'M',
    family: 'Fougère Amaderado',
    occasions: ['diario', 'trabajo', 'cita'],
    feels: ['fresco', 'especiado', 'amaderado'],
    topNotes: 'Bergamota, Pimienta',
    heartNotes: 'Pimienta de Sichuan, Lavanda, Vetiver',
    baseNotes: 'Ambroxan, Cedro',
    duration: '8h+',
    avoidTags: ['gourmand', 'dulce-intenso'],
    sweetness: 1,
    freshness: 4,
    intensity: 4,
    emotionalDesc: 'Un cielo abierto bajo el sol del desierto. El hombre magnético y seguro que domina cualquier recinto al que entra.',
  },
  {
    id: 'fahrenheit-dior',
    name: 'Fahrenheit',
    brand: 'Dior',
    gender: 'M',
    family: 'Almizcle Amaderado Floral',
    occasions: ['noche', 'invierno'],
    feels: ['amaderado', 'especiado'],
    topNotes: 'Flor del moscadero, Lavanda, Mandarina, Manzanilla',
    heartNotes: 'Hoja de violeta, Nuez Moscada, Clavel, Sándalo, Lirio',
    baseNotes: 'Cuero, Vetiver, Almizcle, Ámbar',
    duration: '10h+',
    avoidTags: ['fresco', 'citrico', 'cuero'],
    sweetness: 2,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'El rugido de un motor de combustión y el roce del cuero. Una leyenda masculina que divide, polariza y conquista sin pedir perdón.',
  },
  {
    id: 'eros-flame-versace',
    name: 'Eros Flame',
    brand: 'Versace',
    gender: 'M',
    family: 'Amaderado Especiado',
    occasions: ['noche', 'evento'],
    feels: ['especiado', 'citrico', 'dulce'],
    topNotes: 'Mandarina, Pimienta negra, Limón, Chinotto',
    heartNotes: 'Pimienta, Geranio, Rosa',
    baseNotes: 'Vainilla, Haba Tonka, Sándalo, Cedro de Texas',
    duration: '10h+',
    avoidTags: ['gourmand', 'oud', 'polvo'],
    sweetness: 4,
    freshness: 3,
    intensity: 5,
    emotionalDesc: 'La pasión del dios romano envuelta en llamas rojas. Cálida, imponente y peligrosamente atractiva bajo techo.',
  },
  {
    id: 'dylan-blue-versace',
    name: 'Dylan Blue',
    brand: 'Versace',
    gender: 'M',
    family: 'Fougère Aromático',
    occasions: ['diario', 'verano', 'trabajo'],
    feels: ['fresco', 'citrico', 'amaderado'],
    topNotes: 'Bergamota de Calabria, Toronja, Notas acuáticas',
    heartNotes: 'Ambroxan, Pimienta negra, Papiro, Pachulí',
    baseNotes: 'Incienso, Almizcle, Haba tonka',
    duration: '8h',
    avoidTags: ['dulce-intenso', 'gourmand'],
    sweetness: 2,
    freshness: 5,
    intensity: 4,
    emotionalDesc: 'Las aguas profundas del mar Mediterráneo rompiendo en la costa italiana. Frescura y hombría inagotables.',
  },
  {
    id: 'aventus-creed',
    name: 'Aventus',
    brand: 'Creed',
    gender: 'M',
    family: 'Frutal Chipre',
    occasions: ['trabajo', 'cita', 'evento'],
    feels: ['fresco', 'amaderado', 'frutal'],
    topNotes: 'Piña, Bergamota, Grosellas negras, Manzana',
    heartNotes: 'Abedul, Pachulí, Jazmín marroquí, Rosa',
    baseNotes: 'Almizcle, Musgo de roble, Ámbar gris, Vainilla',
    duration: '10h+',
    avoidTags: ['gourmand', 'dulce-intenso'],
    sweetness: 2,
    freshness: 4,
    intensity: 4,
    emotionalDesc: 'El perfume de reyes y emperadores. Humo oscuro y piña dorada que grita "jefe" desde el instante en que llegas.',
  },
  {
    id: 'silver-mountain-water-creed',
    name: 'Silver Mountain Water',
    brand: 'Creed',
    gender: 'M',
    family: 'Aromático',
    occasions: ['diario', 'verano', 'trabajo'],
    feels: ['fresco', 'citrico', 'acuatico'],
    topNotes: 'Bergamota, Mandarina',
    heartNotes: 'Té verde, Grosellas negras',
    baseNotes: 'Almizcle, Petit grain, Sándalo, Gálbano',
    duration: '6-8h',
    avoidTags: ['intenso', 'dulce-intenso', 'oud', 'especiado'],
    sweetness: 1,
    freshness: 5,
    intensity: 3,
    emotionalDesc: 'Como beber agua de manantial en los alpes suizos. Pureza, elegancia de élite absoluta y refinamiento sereno.',
  },
  {
    id: 'green-irish-tweed-creed',
    name: 'Green Irish Tweed',
    brand: 'Creed',
    gender: 'M',
    family: 'Fougère Clásico',
    occasions: ['trabajo', 'diario'],
    feels: ['fresco', 'amaderado', 'floral'],
    topNotes: 'Cedrón, Iris',
    heartNotes: 'Hoja de violeta',
    baseNotes: 'Ámbar gris, Sándalo',
    duration: '8h',
    avoidTags: ['dulce-intenso', 'gourmand', 'oud', 'polvo'],
    sweetness: 1,
    freshness: 5,
    intensity: 4,
    emotionalDesc: 'El gentleman caminando por la campiña inglesa. La obra maestra que define el concepto de "elegancia de cuna".',
  },
  {
    id: 'invictus-victory-pr',
    name: 'Invictus Victory',
    brand: 'Paco Rabanne',
    gender: 'M',
    family: 'Ámbar',
    occasions: ['noche', 'invierno', 'cita'],
    feels: ['dulce', 'gourmand'],
    topNotes: 'Pimienta rosa, Limón',
    heartNotes: 'Lavanda, Incienso',
    baseNotes: 'Vainilla, Haba tonka, Ámbar',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 5,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Un trofeo oscuro lleno de vainilla e incienso. Indestructible, dulce y ganador en las distancias cortas.',
  },
  {
    id: 'boss-bottled-hugo',
    name: 'Boss Bottled',
    brand: 'Hugo Boss',
    gender: 'M',
    family: 'Amaderado Especiado',
    occasions: ['trabajo', 'diario'],
    feels: ['especiado', 'amaderado', 'frutal'],
    topNotes: 'Manzana, Ciruela, Bergamota, Limón',
    heartNotes: 'Canela, Caoba, Clavel',
    baseNotes: 'Vainilla, Sándalo, Cedro, Vetiver',
    duration: '6-8h',
    avoidTags: ['oud', 'fresco', 'vetiver'],
    sweetness: 3,
    freshness: 3,
    intensity: 3,
    emotionalDesc: 'La firma del ejecutivo impecable. Un clásico absoluto, la manzana asada coronada por maderas sobrias.',
  },
  {
    id: 'hugo-energise',
    name: 'Hugo Energise',
    brand: 'Hugo Boss',
    gender: 'M',
    family: 'Amaderado Aromático',
    occasions: ['diario', 'verano'],
    feels: ['citrico', 'fresco', 'especiado'],
    topNotes: 'Pimienta rosa, Limón, Menta, Piña, Hoja de mandarina',
    heartNotes: 'Fresia, Nuez moscada, Cilantro, Jazmín',
    baseNotes: 'Vainilla, Cuero, Madera de teca',
    duration: '5-7h',
    avoidTags: ['oud', 'gourmand'],
    sweetness: 2,
    freshness: 5,
    intensity: 3,
    emotionalDesc: 'Una inyección vibrante de adrenalina, perfecta para romper la monotonía y conquistar el lunes.',
  },
  {
    id: 'aqva-pour-homme',
    name: 'Aqva Pour Homme',
    brand: 'Bvlgari',
    gender: 'M',
    family: 'Aromático Acuático',
    occasions: ['verano', 'diario'],
    feels: ['fresco', 'citrico', 'acuatico'],
    topNotes: 'Mandarina, Naranja, Petit grain',
    heartNotes: 'Algas marinas, Lavanda, Flor del algodonero',
    baseNotes: 'Cedro de Virginia, Notas amaderadas, Ámbar, Esclarea',
    duration: '6-8h',
    avoidTags: ['dulce-intenso', 'oud', 'gourmand'],
    sweetness: 1,
    freshness: 5,
    intensity: 3,
    emotionalDesc: 'Un clavado hacia las profundidades oscuras y seductoras del océano. Salado, masculino e inquebrantable.',
  },
  {
    id: 'declaration-cartier',
    name: 'Déclaration',
    brand: 'Cartier',
    gender: 'M',
    family: 'Almizcle Amaderado',
    occasions: ['trabajo', 'cita', 'diario'],
    feels: ['especiado', 'amaderado'],
    topNotes: 'Naranja amarga, Alcaravea, Abedul, Bergamota',
    heartNotes: 'Cardamomo guatemalteco, Pimienta, Jengibre, Iris, Madera de enebro',
    baseNotes: 'Vetiver de Tahití, Té, Cedro, Musgo de roble',
    duration: '8h+',
    avoidTags: ['dulce-intenso', 'gourmand', 'fresco', 'vetiver'],
    sweetness: 1,
    freshness: 3,
    intensity: 4,
    emotionalDesc: 'La más fina alta joyería de las maderas y especias. Elegancia cerebral para quien domina las mejores palabras.',
  },
  {
    id: 'santal-33',
    name: 'Santal 33',
    brand: 'Le Labo',
    gender: 'U',
    family: 'Amaderado Aromático',
    occasions: ['diario', 'trabajo', 'cita'],
    feels: ['amaderado', 'especiado'],
    topNotes: 'Cardamomo, Papiro, Violeta',
    heartNotes: 'Iris, Cuero, Ámbar',
    baseNotes: 'Sándalo australiano, Madera de cedro',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico', 'gourmand', 'polvo', 'cuero'],
    sweetness: 1,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'El hipnotismo que incendia la 5ta avenida en Nueva York. Cuero lujoso, sándalo y un rastro de humo verde inconfundible.',
  },
  {
    id: 'le-male-jpg',
    name: 'Le Male',
    brand: 'Jean Paul Gaultier',
    gender: 'M',
    family: 'Ámbar Fougère',
    occasions: ['noche', 'diario', 'cita'],
    feels: ['fresco', 'especiado', 'dulce'],
    topNotes: 'Lavanda, Menta, Cardamomo, Bergamota',
    heartNotes: 'Canela, Flor de azahar, Alcaravea',
    baseNotes: 'Vainilla, Haba tonka, Ámbar, Sándalo',
    duration: '8-10h',
    avoidTags: ['oud'],
    sweetness: 4,
    freshness: 4,
    intensity: 4,
    emotionalDesc: 'El marinero seductor envuelto en una barbería atemporal adornada con vainilla. Un clásico de imán para las atenciones.',
  },
  {
    id: 'ultramale-jpg',
    name: 'Ultra Male',
    brand: 'Jean Paul Gaultier',
    gender: 'M',
    family: 'Ámbar Fougère',
    occasions: ['noche', 'evento'],
    feels: ['dulce', 'frutal'],
    topNotes: 'Pera, Lavanda, Menta, Bergamota',
    heartNotes: 'Canela, Esclarea, Alcaravea',
    baseNotes: 'Vainilla negra, Ámbar, Pachulí, Cedro',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 5,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'El fiestero inagotable. Pera confitada disparando un magnetismo nocturno hecho para no dormir.',
  },
  {
    id: 'ombre-leather-tf',
    name: 'Ombré Leather',
    brand: 'Tom Ford',
    gender: 'U',
    family: 'Cuero',
    occasions: ['noche', 'evento', 'invierno'],
    feels: ['amaderado', 'especiado'],
    topNotes: 'Cardamomo',
    heartNotes: 'Cuero, Jazmín sambac',
    baseNotes: 'Ámbar, Musgo, Pachulí',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico', 'gourmand', 'floral', 'cuero'],
    sweetness: 2,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'El tacto crudo del cuero virgen asoleado sobre un desierto floral. Sex-appeal desenfrenado e intelectual a la vez.',
  },
  {
    id: 'ombre-nomade-lv',
    name: 'Ombre Nomade',
    brand: 'Louis Vuitton',
    gender: 'U',
    family: 'Ámbar Amaderado',
    occasions: ['invierno', 'noche', 'evento'],
    feels: ['oud', 'especiado'],
    topNotes: 'Frambuesa',
    heartNotes: 'Oud, Incienso',
    baseNotes: 'Madera de abedul, Benjuí, Geranio',
    duration: '24h+',
    avoidTags: ['fresco', 'citrico', 'floral', 'oud', 'gourmand'],
    sweetness: 2,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Una tormenta de pura majestad en las dunas doradas del Sahara. Oud infinito de proyección monárquica.',
  },
  {
    id: 'one-million-lucky-pr',
    name: '1 Million Lucky',
    brand: 'Paco Rabanne',
    gender: 'M',
    family: 'Cuero Especiado',
    occasions: ['noche', 'evento'],
    feels: ['dulce', 'especiado'],
    topNotes: 'Cidra, Ozono, Ciruela',
    heartNotes: 'Miel, Avellana, Cedro, Jazmín',
    baseNotes: 'Patchouli, Musgo de roble, Vetiver',
    duration: '8-10h',
    avoidTags: ['fresco-acuatico'],
    sweetness: 4,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Un festival de sensaciones audaces. Dulzura táctil de avellana y miel para el hombre que no teme destacar.',
  },
  {
    id: 'invictus-onix-pr',
    name: 'Invictus Onix',
    brand: 'Paco Rabanne',
    gender: 'M',
    family: 'Amaderada Fresca',
    occasions: ['diario', 'verano', 'trabajo'],
    feels: ['fresco', 'acuatico'],
    topNotes: 'Notas Marinas, Toronja',
    heartNotes: 'Laurel, Jazmín',
    baseNotes: 'Ámbar Gris, Madera de Gaiac, Patchouli',
    duration: '8h+',
    avoidTags: ['dulce-pesado'],
    sweetness: 2,
    freshness: 5,
    intensity: 4,
    emotionalDesc: 'La victoria grabada en piedra negra. Una frescura mineral y profunda que evoca un triunfo imparable.',
  },
  {
    id: 'osadia-male-yanbal',
    name: 'Osadía',
    brand: 'Yanbal',
    gender: 'M',
    family: 'Amaderada Fresca',
    occasions: ['diario', 'cita'],
    feels: ['fresco', 'especiado'],
    topNotes: 'Limón, Yerba Buena',
    heartNotes: 'Especias aromáticas',
    baseNotes: 'Ébano',
    duration: '6-8h',
    avoidTags: ['gourmand'],
    sweetness: 2,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'La picardía del hombre latino. Una mezcla dinámica de limón y maderas oscuras que invita a la conquista.',
  },
  {
    id: 'polo-red-rl',
    name: 'Polo Red',
    brand: 'Ralph Lauren',
    gender: 'M',
    family: 'Amaderada Especiada',
    occasions: ['diario', 'deporte', 'trabajo'],
    feels: ['fresco', 'especiado'],
    topNotes: 'Toronja roja, Arándano, Limón de Italia',
    heartNotes: 'Azafrán rojo, Salvia',
    baseNotes: 'Café, Ámbar, Cedro rojo',
    duration: '6h',
    avoidTags: ['oud', 'floral'],
    sweetness: 2,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'Adrenalina pura en una botella roja. Cítricos vibrantes y un toque de café para un día lleno de acción.',
  },
  {
    id: 'santos-cartier-male',
    name: 'Santos',
    brand: 'Cartier',
    gender: 'M',
    family: 'Ámbar Amaderada',
    occasions: ['evento', 'trabajo', 'noche'],
    feels: ['amaderado', 'especiado'],
    topNotes: 'Lavanda, Albahaca, Bergamota',
    heartNotes: 'Nuez Moscada, Comino, Enebro',
    baseNotes: 'Sándalo, Patchouli, Ámbar',
    duration: '10h+',
    avoidTags: ['dulce-gourmand'],
    sweetness: 1,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'Un tributo al pionero Santos Dumont. Elegancia clásica, madura y profundamente masculina.',
  },
  {
    id: 'scandal-homme-jpg',
    name: 'Scandal Pour Homme',
    brand: 'Jean Paul Gaultier',
    gender: 'M',
    family: 'Ámbar Amaderada',
    occasions: ['noche', 'evento', 'cita'],
    feels: ['dulce', 'gourmand'],
    topNotes: 'Esclarea, Mandarina',
    heartNotes: 'Caramelo, Haba Tonka',
    baseNotes: 'Vetiver',
    duration: '12h+',
    avoidTags: ['acuatico', 'fresco-ligero'],
    sweetness: 5,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'El rey del ring nocturno. Un golpe maestro de caramelo y maderas que no deja a nadie indiferente.',
  },
  {
    id: 'solo-loewe-male',
    name: 'Solo Loewe',
    brand: 'Loewe',
    gender: 'M',
    family: 'Ámbar Especiada',
    occasions: ['trabajo', 'evento', 'diario'],
    feels: ['fresco', 'especiado', 'amaderado'],
    topNotes: 'Guayaba, Lavanda, Mandarina',
    heartNotes: 'Pimienta rosa, Canela, Nuez moscada',
    baseNotes: 'Ámbar, Almizcle, Notas amaderadas',
    duration: '8h+',
    avoidTags: ['acuatico-marino'],
    sweetness: 2,
    freshness: 3,
    intensity: 4,
    emotionalDesc: 'El equilibrio entre los extremos. Maderas y especias que logran una armonía sofisticada y duradera.',
  },
  {
    id: 'solo-male-yanbal',
    name: 'Solo',
    brand: 'Yanbal',
    gender: 'M',
    family: 'Cuero fresco',
    occasions: ['trabajo', 'diario'],
    feels: ['limpio', 'cuero'],
    topNotes: 'Hoja de Higo',
    heartNotes: 'Jengibre',
    baseNotes: 'Cuero',
    duration: '8h',
    avoidTags: ['dulce-pesado'],
    sweetness: 1,
    freshness: 4,
    intensity: 4,
    emotionalDesc: 'Impecable como una camisa recién planchada. La frescura del jengibre sobre un cuero refinado y limpio.',
  },
  {
    id: 'spicebomb-vr',
    name: 'Spicebomb',
    brand: 'Viktor & Rolf',
    gender: 'M',
    family: 'Amaderada Especiada',
    occasions: ['noche', 'invierno', 'cita'],
    feels: ['especiado', 'dulce', 'amaderado'],
    topNotes: 'Pimienta Rosa, Bergamota, Toronja',
    heartNotes: 'Canela, Azafrán, Paprika',
    baseNotes: 'Tabaco, Cuero, Vetiver',
    duration: '10h+',
    avoidTags: ['acuatico', 'floral'],
    sweetness: 3,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'Una explosión sensorial. Canela ardiente y tabaco que crean un aura de seducción irresistible.',
  },
  {
    id: 'stronger-with-you-ea',
    name: 'Stronger With You',
    brand: 'Emporio Armani',
    gender: 'M',
    family: 'Aromática Fougère',
    occasions: ['cita', 'noche', 'invierno'],
    feels: ['dulce', 'especiado'],
    topNotes: 'Cardamomo, Pimienta Rosa, Hojas de violeta, Menta',
    heartNotes: 'Piña, Salvia, Melón, Canela, Lavanda',
    baseNotes: 'Vainilla, Castaña, Ámbar, Cedro',
    duration: '10h+',
    avoidTags: ['acuatico', 'citrico-ligero'],
    sweetness: 5,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'El magnetismo de la unión. Castaña dulce y vainilla para un hombre moderno, cálido y seguro.',
  },
  {
    id: 'most-wanted-azzaro',
    name: 'The Most Wanted',
    brand: 'Azzaro',
    gender: 'M',
    family: 'Ámbar Especiada',
    occasions: ['noche', 'cita', 'evento'],
    feels: ['dulce', 'especiado'],
    topNotes: 'Cardamomo',
    heartNotes: 'Toffee',
    baseNotes: 'Amberwood',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 5,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'El arma definitiva de seducción. Cardamomo intenso y un fondo de toffee adictivo.',
  },
  {
    id: 'the-one-male-dg',
    name: 'The One for Men',
    brand: 'Dolce & Gabbana',
    gender: 'M',
    family: 'Amaderada Especiada',
    occasions: ['cita', 'trabajo', 'evento'],
    feels: ['especiado', 'amaderado'],
    topNotes: 'Cilantro, Albahaca, Toronja',
    heartNotes: 'Jengibre, Flor de Azahar, Cardamomo',
    baseNotes: 'Ámbar, Tabaco, Cedro',
    duration: '8h',
    avoidTags: ['acuatico-fuerte'],
    sweetness: 3,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Un clásico mediterráneo. Sofisticación masculina pura con un rastro cálido de tabaco y ámbar.',
  },
  {
    id: 'tommy-hilfiger-male',
    name: 'Tommy',
    brand: 'Tommy Hilfiger',
    gender: 'M',
    family: 'Cítrica Aromática',
    occasions: ['diario', 'verano', 'deporte'],
    feels: ['fresco', 'citrico', 'verde'],
    topNotes: 'Menta, Lavanda, Toronja, Bergamota',
    heartNotes: 'Arándano, Rosa, Manzana',
    baseNotes: 'Ámbar, Cactus, Flor del Algodonero',
    duration: '6h',
    avoidTags: ['dulce-pesado', 'oud'],
    sweetness: 1,
    freshness: 5,
    intensity: 2,
    emotionalDesc: 'La frescura del sueño americano. Un aroma limpio, juvenil y lleno de energía.',
  },
  {
    id: 'toy-boy-moschino-male',
    name: 'Toy Boy',
    brand: 'Moschino',
    gender: 'M',
    family: 'Amaderada Especiada',
    occasions: ['evento', 'cita', 'evento'],
    feels: ['floral', 'especiado', 'amaderado'],
    topNotes: 'Pimienta Rosa, Pera, Nuez Moscada, Bergamota',
    heartNotes: 'Rosa, Magnolia, Clavo de olor, Lino',
    baseNotes: 'Sándalo, Cashmeran, Ámbar, Vetiver',
    duration: '10h+',
    avoidTags: ['acuatico', 'citrico-simple'],
    sweetness: 3,
    freshness: 3,
    intensity: 5,
    emotionalDesc: 'Provocativo e iconoclasta. Una rosa masculina oscura rodeada de especias que rompe todos los moldes.',
  },
  {
    id: 'uomo-valentino-male',
    name: 'Valentino Uomo',
    brand: 'Valentino',
    gender: 'M',
    family: 'Ámbar Amaderada',
    occasions: ['cita', 'noche', 'trabajo'],
    feels: ['dulce', 'amaderado', 'limpio'],
    topNotes: 'Bergamota, Mirto',
    heartNotes: 'Café tostado, Chocolate, Avellana',
    baseNotes: 'Cuero, Cedro',
    duration: '8-10h',
    avoidTags: ['acuatico', 'verde-fuerte'],
    sweetness: 4,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Elegancia romana. Café y chocolate blanco sobre un cuero lujoso, perfecto para un gentleman moderno.',
  },
  {
    id: 'victory-invictus-male',
    name: 'Invictus Victory',
    brand: 'Paco Rabanne',
    gender: 'M',
    family: 'Ámbar',
    occasions: ['invierno', 'noche', 'evento'],
    feels: ['dulce', 'gourmand'],
    topNotes: 'Limón, Pimienta Rosa',
    heartNotes: 'Incienso, Lavanda',
    baseNotes: 'Vainilla, Haba Tonka, Ámbar',
    duration: '12h+',
    avoidTags: ['fresco-ligero'],
    sweetness: 5,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'El trofeo oscuro definitivo. Una vainilla ahumada y poderosa para el hombre que solo conoce el éxito.',
  },
  {
    id: 'voyage-nautica-male',
    name: 'Nautica Voyage',
    brand: 'Nautica',
    gender: 'M',
    family: 'Amaderada Acuática',
    occasions: ['diario', 'verano', 'deporte'],
    feels: ['fresco', 'acuatico'],
    topNotes: 'Manzana verde, Hojas verdes',
    heartNotes: 'Loto, Mimosa',
    baseNotes: 'Almizcle, Cedro, Musgo de roble, Ámbar',
    duration: '6h',
    avoidTags: ['dulce-pesado', 'especiado'],
    sweetness: 2,
    freshness: 5,
    intensity: 3,
    emotionalDesc: 'La brisa del océano en calma. Manzana fresca y notas acuáticas para un día bajo el sol radiante.',
  },
  {
    id: 'y-ysl-male',
    name: 'Y Eau de Parfum',
    brand: 'Yves Saint Laurent',
    gender: 'M',
    family: 'Aromática Fougère',
    occasions: ['trabajo', 'diario', 'evento'],
    feels: ['fresco', 'amaderado'],
    topNotes: 'Manzana, Jengibre, Bergamota',
    heartNotes: 'Salvia, Bayas de Enebro, Geranio',
    baseNotes: 'Amberwood, Haba Tonka, Cedro, Vetiver, Incienso',
    duration: '10h+',
    avoidTags: ['dulce-gourmand'],
    sweetness: 2,
    freshness: 4,
    intensity: 5,
    emotionalDesc: 'La esencia de la generación Y. Un equilibrio perfecto entre frescura cítrica y maderas profundas.',
  },
  {
    id: 'zlatan-ibrahimovic-male',
    name: 'Zlatan',
    brand: 'Zlatan Ibrahimovic',
    gender: 'M',
    family: 'Aromática Acuática',
    occasions: ['deporte', 'diario'],
    feels: ['fresco', 'acuatico'],
    topNotes: 'Limón, Especias',
    heartNotes: 'Notas Marinas',
    baseNotes: 'Maderas blancas',
    duration: '5-7h',
    avoidTags: ['floral', 'dulce-pesado'],
    sweetness: 1,
    freshness: 5,
    intensity: 3,
    emotionalDesc: 'Energía deportiva pura. Un aroma directo, fresco y masculino para el máximo rendimiento.',
  },
];
