import type { Perfume } from '../types';

export const nichoPerfumes: Perfume[] = [
  {
    id: 'baccarat-rouge-540',
    name: 'Baccarat Rouge 540',
    brand: 'Maison Francis Kurkdjian',
    gender: 'U',
    family: 'Ámbar Floral',
    occasions: ['evento', 'noche', 'cita'],
    feels: ['dulce', 'amaderado'],
    topNotes: 'Azafrán, Jazmín',
    heartNotes: 'Amberwood, Ámbar gris',
    baseNotes: 'Resina de abeto, Cedro',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 5,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'El aura del lujo absoluto. Un aroma que flota como oro líquido en el aire, dulce y amaderado.',
  },
  {
    id: 'erba-pura-sospiro',
    name: 'Erba Pura',
    brand: 'Xerjoff',
    gender: 'U',
    family: 'Ámbar Frutal',
    occasions: ['diario', 'evento', 'evento'],
    feels: ['frutal', 'dulce', 'fresco'],
    topNotes: 'Naranja de Sicilia, Bergamota de Calabria, Limón de Sicilia',
    heartNotes: 'Frutas',
    baseNotes: 'Almizcle blanco, Vainilla de Madagascar, Ámbar',
    duration: '12h+',
    avoidTags: ['oud', 'cuero'],
    sweetness: 4,
    freshness: 4,
    intensity: 5,
    emotionalDesc: 'Una explosión de frutas mediterráneas sobre un fondo de almizcle aterciopelado. Energía pura.',
  },
  {
    id: 'kirke-tiziana-terenzi',
    name: 'Kirke',
    brand: 'Tiziana Terenzi',
    gender: 'U',
    family: 'Chipre Frutal',
    occasions: ['diario', 'verano', 'evento'],
    feels: ['frutal', 'dulce', 'fresco'],
    topNotes: 'Maracuyá, Melocotón, Pera, Frambuesa, Cassis, Arena',
    heartNotes: 'Lirio de los valles',
    baseNotes: 'Almizcle, Sándalo, Vainilla, Pachulí, Heliotropo',
    duration: '12h+',
    avoidTags: ['oud', 'especiado-pesado'],
    sweetness: 4,
    freshness: 4,
    intensity: 5,
    emotionalDesc: 'Una poción mágica inspirada en la diosa Circe. Un viaje frutal intenso y magnético.',
  },
  {
    id: 'naxos-xerjoff',
    name: 'Naxos',
    brand: 'Xerjoff',
    gender: 'U',
    family: 'Aromática Especiada',
    occasions: ['cita', 'noche', 'invierno'],
    feels: ['dulce', 'amaderado', 'especiado'],
    topNotes: 'Lavanda, Bergamota, Limón',
    heartNotes: 'Miel, Canela, Cachemira, Jazmín sambac',
    baseNotes: 'Hoja de tabaco, Vainilla, Haba tonka',
    duration: '12h+',
    avoidTags: ['acuatico', 'fresco-ligero'],
    sweetness: 4,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'El corazón de Sicilia embotellado. Miel dorada y tabaco suave para una elegancia suprema.',
  },
  {
    id: 'megamare-orto-parisi',
    name: 'Megamare',
    brand: 'Orto Parisi',
    gender: 'U',
    family: 'Aromática Acuática',
    occasions: ['diario', 'trabajo', 'verano'],
    feels: ['fresco', 'acuatico'],
    topNotes: 'Notas marinas',
    heartNotes: 'Algas marinas',
    baseNotes: 'Ámbar, Almizcle',
    duration: '24h+',
    avoidTags: ['dulce', 'gourmand'],
    sweetness: 1,
    freshness: 5,
    intensity: 5,
    emotionalDesc: 'La fuerza indomable del océano profundo. Salado, oscuro e infinito.',
  },
  {
    id: 'oud-maracuja-maison-crivelli',
    name: 'Oud Maracuja',
    brand: 'Maison Crivelli',
    gender: 'U',
    family: 'Exótico Amaderado Frutal',
    occasions: ['noche', 'evento', 'cita'],
    feels: ['oud', 'frutal', 'amaderado'],
    topNotes: 'Maracuyá, Azafrán, Rosa Turca',
    heartNotes: 'Patchouli de Indonesia, Benjuí',
    baseNotes: 'Cuero, Ámbar Vainilla, Labdanum, Akigalawood',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico-ligero'],
    sweetness: 3,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'Un contraste magistral entre la maracuyá jugosa y el calor tropical del oud. Adictivo y ardiente.',
  },
  {
    id: 'summer-hammer-lorenzo-pazzaglia',
    name: 'Summer Hammer',
    brand: 'Lorenzo Pazzaglia',
    gender: 'U',
    family: 'Amaderado Frutal',
    occasions: ['verano', 'evento', 'diario'],
    feels: ['dulce', 'frutal', 'fresco'],
    topNotes: 'Mango, Piña, Coco, Ron Blanco',
    heartNotes: 'Leche de Coco, Notas Marinas, Flores Blancas',
    baseNotes: 'Vetiver, Almizcle, Sándalo, Ámbar Indio',
    duration: '12h+',
    avoidTags: ['oud', 'invierno'],
    sweetness: 5,
    freshness: 4,
    intensity: 5,
    emotionalDesc: 'Una Piña Colada atómica. Dulzura tropical extrema que dura todo el día bajo el sol.',
  },
  {
    id: 'bianco-latte-giardini-di-toscana',
    name: 'Bianco Latte',
    brand: 'Giardini di Toscana',
    gender: 'U',
    family: 'Lactónico Gourmand',
    occasions: ['diario', 'cita', 'invierno'],
    feels: ['dulce', 'gourmand'],
    topNotes: 'Miel',
    heartNotes: 'Caramelo',
    baseNotes: 'Vainilla, Almizcle Blanco',
    duration: '10h+',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 5,
    freshness: 1,
    intensity: 4,
    emotionalDesc: 'Un abrazo olfativo. Caramelo y vainilla cremosa que se siente como una caricia suave.',
  },
  {
    id: 'atomic-rose-initio',
    name: 'Atomic Rose',
    brand: 'Initio',
    gender: 'U',
    family: 'Floral Oriental',
    occasions: ['evento', 'noche', 'cita'],
    feels: ['floral', 'amaderado'],
    topNotes: 'Bergamota de Italia, Pimienta Rosa',
    heartNotes: 'Rosa de Bulgaria, Rosa Turca, Jazmín Egipcio',
    baseNotes: 'Vainilla de Madagascar, Ámbar',
    duration: '12h+',
    avoidTags: ['fresco-ligero', 'verde'],
    sweetness: 3,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'Una rosa narcótica cargada de energía. Potente, lujosa y capaz de llenar cualquier espacio.',
  },
  {
    id: 'aventus-for-her-creed',
    name: 'Aventus for Her',
    brand: 'Creed',
    gender: 'F',
    family: 'Fruity Floral',
    occasions: ['trabajo', 'evento', 'diario'],
    feels: ['fresco', 'floral', 'frutal'],
    topNotes: 'Manzana verde, Pimienta Rosa, Bergamota',
    heartNotes: 'Rosa, Sándalo, Styrax, Almizcle',
    baseNotes: 'Ámbar, Ylang-Ylang, Melocotón, Grosella negra',
    duration: '10h+',
    avoidTags: ['gourmand', 'dulce-intenso'],
    sweetness: 2,
    freshness: 4,
    intensity: 4,
    emotionalDesc: 'La contraparte femenina del ícono. Empoderada, brillante y con una elegancia que manda.',
  },
  {
    id: 'intense-cafe-montale',
    name: 'Intense Cafe',
    brand: 'Montale',
    gender: 'U',
    family: 'Ámbar Vainilla',
    occasions: ['noche', 'invierno', 'cita'],
    feels: ['dulce', 'floral', 'gourmand'],
    topNotes: 'Notas Florales',
    heartNotes: 'Rosa, Café',
    baseNotes: 'Vainilla, Almizcle Blanco, Ámbar',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico-ligero'],
    sweetness: 4,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Un café recién hecho rodeado de rosas frescas. Una experiencia acogedora y sumamente duradera.',
  },
  {
    id: 'psychedelic-love-initio',
    name: 'Psychedelic Love',
    brand: 'Initio',
    gender: 'U',
    family: 'Floral Amaderada',
    occasions: ['cita', 'noche', 'evento'],
    feels: ['floral', 'amaderado'],
    topNotes: 'Ylang-Ylang, Bergamota',
    heartNotes: 'Heliotropo, Rosa de Bulgaria, Hedione',
    baseNotes: 'Sándalo, Mirra',
    duration: '10h+',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 3,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Un aroma transgresivo y adictivo. Cremoso, floral y con un magnetismo casi psicodélico.',
  },
  {
    id: 'sun-kissed-goddess-kilian',
    name: 'Sun Kissed Goddess',
    brand: 'Kilian',
    gender: 'U',
    family: 'Floral Solar',
    occasions: ['verano', 'evento', 'diario'],
    feels: ['floral', 'fresco', 'dulce'],
    topNotes: 'Bergamota, Neroli',
    heartNotes: 'Flor de Tiaré, Ylang-Ylang',
    baseNotes: 'Coco, Vainilla, Madera de Guayaco',
    duration: '8h+',
    avoidTags: ['invierno', 'oud'],
    sweetness: 4,
    freshness: 3,
    intensity: 4,
    emotionalDesc: 'Piel bronceada, arena caliente y sol. El aroma de unas vacaciones de lujo eterno.',
  },
  {
    id: 'arabian-tonka-montale',
    name: 'Arabians Tonka',
    brand: 'Montale',
    gender: 'U',
    family: 'Ámbar Amaderada',
    occasions: ['noche', 'invierno', 'evento'],
    feels: ['dulce', 'oud', 'especiado'],
    topNotes: 'Azafrán, Bergamota',
    heartNotes: 'Oud, Rosa de Bulgaria',
    baseNotes: 'Haba Tonka, Caña de azúcar, Ámbar, Almizcle blanco, Musgo de roble',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 4,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Un semental árabe galopando en la noche. Dulzura ahumada y haba tonka que proyecta una fuerza imparable.',
  },
  {
    id: 'il-femme-ilmin',
    name: 'Il Femme',
    brand: 'Ilmin',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'trabajo', 'cita'],
    feels: ['floral', 'frutal', 'fresco'],
    topNotes: 'Manzana, Grosella Negra, Notas Verdes',
    heartNotes: 'Jazmín, Rosa, Lirio de los valles',
    baseNotes: 'Almizcle, Sándalo, Ámbar',
    duration: '8h+',
    avoidTags: ['oud', 'especiado-pesado'],
    sweetness: 3,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'La sofisticación francesa de nicho. Un ramo floral con destellos frutales que irradia una feminidad moderna y limpia.',
  },
  {
    id: 'narcotic-delight-initio',
    name: 'Narcotic Delight',
    brand: 'Initio',
    gender: 'U',
    family: 'Ámbar Vainilla',
    occasions: ['noche', 'cita', 'invierno'],
    feels: ['dulce', 'especiado', 'gourmand'],
    topNotes: 'Cereza, Pimienta Rosa, Pimienta Negra',
    heartNotes: 'Coñac, Hedione',
    baseNotes: 'Tabaco, Vainilla',
    duration: '10h+',
    avoidTags: ['fresco', 'acuatico'],
    sweetness: 4,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Un placer prohibido. Cereza oscura, tabaco y coñac que crean una atmósfera hipnótica y sumamente sensual.',
  },
  {
    id: 'queen-of-silk-creed',
    name: 'Queen of Silk',
    brand: 'Creed',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['evento', 'noche', 'cita'],
    feels: ['floral', 'dulce', 'amaderado'],
    topNotes: 'Azafrán, Osmanto, Magnolia',
    heartNotes: 'Nardos, Maracuyá, Pachulí, Agarwood',
    baseNotes: 'Vainilla de Madagascar, Incienso, Mirra, Ambroxan, Cedro',
    duration: '10h+',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 3,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'La elegancia de la seda pura. Un velo lujoso de flores blancas y resinas preciosas que envuelve con distinción real.',
  },
  {
    id: 'roses-musk-montale',
    name: 'Roses Musk',
    brand: 'Montale',
    gender: 'F',
    family: 'Floral Almizclada',
    occasions: ['diario', 'cita', 'trabajo'],
    feels: ['floral', 'fresco'],
    topNotes: 'Rosa',
    heartNotes: 'Jazmín',
    baseNotes: 'Almizcle, Ámbar',
    duration: '12h+',
    avoidTags: ['dulce-pesado', 'oud'],
    sweetness: 2,
    freshness: 3,
    intensity: 5,
    emotionalDesc: 'La rosa más pura y limpia del mundo. Un aura de almizcle que proyecta frescura y sensualidad impecable.',
  },
];
