import type { Perfume } from '../types';

export const catalog: Perfume[] = [
  // ── MASCULINOS ─────────────────────────────────────
  {
    id: 'sauvage-elixir',
    name: 'Sauvage Elixir',
    brand: 'Dior',
    gender: 'M',
    family: 'Fougère Amaderado',
    occasions: ['noche', 'invierno', 'cita', 'evento'],
    feels: ['especiado', 'amaderado', 'fresco'],
    topNotes: 'Pomelo, Canela',
    heartNotes: 'Lavanda, Nuez moscada',
    baseNotes: 'Sándalo, Vetiver, Ámbar',
    duration: '10-12h',
    avoidTags: ['especias', 'intenso', 'vetiver'],
    sweetness: 2,
    freshness: 3,
    intensity: 5,
    emotionalDesc: 'Un rugido contenido. Para el hombre que entra a una habitación y hace que todos volteen… sin decir una sola palabra.',
  },
  {
    id: 'centaurus',
    name: 'Centaurus',
    brand: 'Creed',
    gender: 'M',
    family: 'Aromático Amaderado',
    occasions: ['diario', 'trabajo', 'cita'],
    feels: ['fresco', 'amaderado', 'citrico'],
    topNotes: 'Bergamota, Limón',
    heartNotes: 'Cedro, Iris',
    baseNotes: 'Musgo de roble, Vetiver',
    duration: '8-10h',
    avoidTags: ['vetiver', 'polvo'],
    sweetness: 1,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'Lujo silencioso. La fragancia del hombre que no necesita gritar para ser notado. Bergamota que evoluciona hacia madera con nobleza.',
  },
  {
    id: 'il-kakuno',
    name: 'Il Kakuno',
    brand: 'ILMIN',
    gender: 'M',
    family: 'Frutal Amaderado',
    occasions: ['diario', 'verano', 'trabajo'],
    feels: ['frutal', 'fresco', 'amaderado'],
    topNotes: 'Caqui, Bergamota',
    heartNotes: 'Magnolia, Palisandro',
    baseNotes: 'Vetiver, Musgo',
    duration: '6-8h',
    avoidTags: ['polvo', 'vetiver'],
    sweetness: 2,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'Un atardecer japonés en tu piel. Frutal, único y con una elegancia discreta que solo los entendidos reconocen.',
  },
  {
    id: 'summer-hammer',
    name: 'Summer Hammer',
    brand: 'Lorenzo Pazzaglia',
    gender: 'M',
    family: 'Acuático Fresco',
    occasions: ['verano', 'diario'],
    feels: ['fresco', 'acuatico', 'citrico'],
    topNotes: 'Lima, Aldehídos',
    heartNotes: 'Flor de Tiaré, Coco',
    baseNotes: 'Musco, Almizcle',
    duration: '5-7h',
    avoidTags: ['pesado'],
    sweetness: 2,
    freshness: 5,
    intensity: 2,
    emotionalDesc: 'Brisa del Mediterráneo embotellada. Te lleva a una terraza frente al mar aunque estés en la oficina.',
  },
  {
    id: 'emeer',
    name: 'Emeer',
    brand: 'Lattafa',
    gender: 'M',
    family: 'Oriental Amaderado',
    occasions: ['noche', 'invierno', 'evento'],
    feels: ['amaderado', 'especiado', 'oud'],
    topNotes: 'Oud, Rosa',
    heartNotes: 'Jasmín, Sándalo',
    baseNotes: 'Ládano, Ámbar, Almizcle',
    duration: '12h+',
    avoidTags: ['oud', 'especias', 'intenso'],
    sweetness: 3,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Misterio árabe en estado puro. Intensa, sensual, y absolutamente imposible de olvidar. Una declaración de poder.',
  },
  {
    id: 'royal-amber',
    name: 'Royal Amber',
    brand: 'Orientica',
    gender: 'M',
    family: 'Oriental Ambarino',
    occasions: ['noche', 'invierno', 'evento', 'cita'],
    feels: ['amaderado', 'dulce', 'especiado'],
    topNotes: 'Azafrán, Rosa',
    heartNotes: 'Oud, Sándalo',
    baseNotes: 'Ámbar, Benjuí, Vainilla',
    duration: '12h+',
    avoidTags: ['oud', 'dulce-intenso', 'intenso'],
    sweetness: 4,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Como envolverse en terciopelo dorado. Cálida, majestuosa y suntuosa. Para quienes nunca pasan desapercibidos.',
  },
  {
    id: '9pm-rebel',
    name: '9PM Rebel',
    brand: 'Afnan',
    gender: 'M',
    family: 'Aromático Suave',
    occasions: ['noche', 'cita', 'evento'],
    feels: ['dulce', 'especiado', 'amaderado'],
    topNotes: 'Manzana, Lavanda',
    heartNotes: 'Cardamomo, Canela',
    baseNotes: 'Vainilla, Musgo, Cachemira',
    duration: '8-10h',
    avoidTags: ['dulce-intenso'],
    sweetness: 4,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Tu aliada para las noches sin nombre. Dulce con carácter, perfecta para quien rompe las reglas con estilo propio.',
  },
  {
    id: 'asad',
    name: 'Asad',
    brand: 'Lattafa',
    gender: 'M',
    family: 'Oriental Especiado',
    occasions: ['noche', 'invierno', 'evento'],
    feels: ['especiado', 'amaderado', 'dulce'],
    topNotes: 'Naranja, Canela',
    heartNotes: 'Oud, Sándalo',
    baseNotes: 'Ámbar, Almizcle, Vainilla',
    duration: '10-12h',
    avoidTags: ['oud', 'especias', 'intenso'],
    sweetness: 3,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'El León en su esplendor. Poderoso, especiado y ferozmente animal. Solo para quienes no temen que los recuerden.',
  },
  {
    id: 'khamrah',
    name: 'Khamrah',
    brand: 'Lattafa',
    gender: 'U',
    family: 'Oriental Gourmand',
    occasions: ['noche', 'invierno', 'cita'],
    feels: ['dulce', 'especiado', 'gourmand'],
    topNotes: 'Canela, Nuez Moscada',
    heartNotes: 'Jazmín, Oud',
    baseNotes: 'Vainilla, Ámbar, Caramelo',
    duration: '12h+',
    avoidTags: ['dulce-intenso', 'oud', 'intenso'],
    sweetness: 5,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Un postre de alta perfumería. Dulce sin disculpas, adictiva y magnética. La que todos te preguntan qué llevas puesto.',
  },
  {
    id: 'oud-maracuja',
    name: 'Oud Maracujá',
    brand: 'Maison Crivelli',
    gender: 'U',
    family: 'Frutal Oriental',
    occasions: ['noche', 'cita', 'evento'],
    feels: ['frutal', 'oud', 'especiado'],
    topNotes: 'Maracuyá, Pimienta Rosa',
    heartNotes: 'Oud, Jazmín',
    baseNotes: 'Vetiver, Musgo, Ámbar',
    duration: '10-12h',
    avoidTags: ['oud', 'vetiver'],
    sweetness: 3,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'El trópico se encuentra con Oriente en una danza inesperada y fascinante. Para quienes aman la originalidad radical.',
  },
  {
    id: 'ahli-vega',
    name: 'Ahli Vega',
    brand: 'Ahli',
    gender: 'M',
    family: 'Fougère Fresco',
    occasions: ['diario', 'trabajo', 'verano'],
    feels: ['fresco', 'citrico', 'amaderado'],
    topNotes: 'Bergamota, Pomelo',
    heartNotes: 'Lavanda, Menta',
    baseNotes: 'Cedro, Musgo, Almizcle',
    duration: '6-8h',
    avoidTags: ['pesado'],
    sweetness: 1,
    freshness: 5,
    intensity: 2,
    emotionalDesc: 'Frescura herbal que despierta los sentidos. El equivalente olfativo de caminar por un jardín al amanecer después de la lluvia.',
  },
  {
    id: 'nitro-red',
    name: 'Nitro Red',
    brand: 'Dumont',
    gender: 'M',
    family: 'Aromático Especiado',
    occasions: ['noche', 'cita', 'invierno'],
    feels: ['especiado', 'dulce', 'amaderado'],
    topNotes: 'Bergamota, Manzana',
    heartNotes: 'Canela, Cardamomo',
    baseNotes: 'Vainilla, Sándalo, Ámbar',
    duration: '8-10h',
    avoidTags: ['especias'],
    sweetness: 4,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Energía especiada que enciende la noche. Para el que llega y quiere que se note. Audaz sin ser agresivo.',
  },
  {
    id: 'ohm-yanbal',
    name: 'Öhm',
    brand: 'Yanbal',
    gender: 'M',
    family: 'Amaderado Aromático',
    occasions: ['diario', 'trabajo'],
    feels: ['amaderado', 'fresco', 'citrico'],
    topNotes: 'Bergamota, Jengibre',
    heartNotes: 'Cedro, Lavanda',
    baseNotes: 'Sándalo, Vetiver, Almizcle',
    duration: '6-8h',
    avoidTags: ['pesado', 'vetiver'],
    sweetness: 1,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'El equilibrio perfecto entre frescura y calidez. Tu compañero fiel de lunes a viernes que nunca desentona.',
  },
  {
    id: 'solo-yanbal',
    name: 'Solo',
    brand: 'Yanbal',
    gender: 'M',
    family: 'Aromático Fresco',
    occasions: ['diario', 'trabajo', 'verano'],
    feels: ['fresco', 'citrico', 'amaderado'],
    topNotes: 'Lima, Bergamota',
    heartNotes: 'Salvia, Romero',
    baseNotes: 'Musgo de Roble, Cedro',
    duration: '5-7h',
    avoidTags: [],
    sweetness: 1,
    freshness: 5,
    intensity: 2,
    emotionalDesc: 'Limpio, fresco, inequívocamente masculino. La elección del hombre seguro de sí mismo que no necesita impresionar a nadie.',
  },
  {
    id: 'jean-marie-farina',
    name: 'Jean Marie Farina',
    brand: 'Roger & Gallet',
    gender: 'U',
    family: 'Cítrico Aromático',
    occasions: ['diario', 'verano', 'trabajo'],
    feels: ['citrico', 'fresco', 'floral'],
    topNotes: 'Bergamota, Naranja, Limón',
    heartNotes: 'Neroli, Petigrain',
    baseNotes: 'Musgo, Madera suave',
    duration: '4-6h',
    avoidTags: [],
    sweetness: 1,
    freshness: 5,
    intensity: 2,
    emotionalDesc: 'Historia líquida desde 1806. La elegancia de lo simple, de lo eterno. Una joya que no necesita gritar para ser reconocida.',
  },
  {
    id: 'bleu-chanel',
    name: 'Bleu de Chanel',
    brand: 'Chanel',
    gender: 'M',
    family: 'Amaderado Aromático',
    occasions: ['diario', 'trabajo', 'cita'],
    feels: ['fresco', 'amaderado', 'especiado'],
    topNotes: 'Limón, Menta, Pomelo',
    heartNotes: 'Jengibre, Nuez Moscada, Jazmín',
    baseNotes: 'Sándalo, Cedro, Madera de Incienso',
    duration: '8-10h',
    avoidTags: [],
    sweetness: 2,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'El perfume de los hombres que saben exactamente quiénes son. Moderno, multifacético e intemporalmente Chanel.',
  },
  {
    id: 'acqua-di-gio',
    name: 'Acqua di Giò',
    brand: 'Giorgio Armani',
    gender: 'M',
    family: 'Acuático Aromático',
    occasions: ['verano', 'diario', 'trabajo'],
    feels: ['fresco', 'acuatico', 'citrico'],
    topNotes: 'Limón, Bergamota, Lima',
    heartNotes: 'Jazmín marino, Calone, Romero',
    baseNotes: 'Cedro, Vetiver, Patchouli',
    duration: '6-8h',
    avoidTags: ['pesado', 'vetiver'],
    sweetness: 1,
    freshness: 5,
    intensity: 2,
    emotionalDesc: 'El mar en tu piel. Un clásico contemporáneo que nunca decepciona y que cualquiera reconoce como distinción.',
  },
  {
    id: 'one-million',
    name: '1 Million',
    brand: 'Paco Rabanne',
    gender: 'M',
    family: 'Oriental Especiado',
    occasions: ['noche', 'cita', 'evento', 'invierno'],
    feels: ['especiado', 'dulce', 'amaderado'],
    topNotes: 'Mandarina, Pomelo, Menta',
    heartNotes: 'Rosa, Canela, Jengibre',
    baseNotes: 'Ámbar, Cuero, Patchouli',
    duration: '8-10h',
    avoidTags: ['cuero', 'especias'],
    sweetness: 4,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Magnético como el oro. Convierte cualquier salida nocturna en un momento cinematográfico que nadie olvida.',
  },
  {
    id: 'ultra-male',
    name: 'Ultra Male',
    brand: 'Jean Paul Gaultier',
    gender: 'M',
    family: 'Oriental Fougère',
    occasions: ['noche', 'cita', 'invierno'],
    feels: ['dulce', 'especiado', 'frutal'],
    topNotes: 'Pera, Lavanda',
    heartNotes: 'Menta, Iris',
    baseNotes: 'Vainilla, Sándalo, Ámbar',
    duration: '10-12h',
    avoidTags: ['dulce-intenso', 'intenso'],
    sweetness: 5,
    freshness: 2,
    intensity: 5,
    emotionalDesc: 'Audazmente dulce y ferozmente masculino a la vez. Para el hombre sin complejos que abraza todo su encanto.',
  },
  {
    id: 'boss-bottled',
    name: 'Boss Bottled',
    brand: 'Hugo Boss',
    gender: 'M',
    family: 'Frutal Aromático',
    occasions: ['diario', 'trabajo', 'cita'],
    feels: ['frutal', 'especiado', 'amaderado'],
    topNotes: 'Manzana, Cítricos, Ciruelas',
    heartNotes: 'Canela, Clavel, Violeta',
    baseNotes: 'Sándalo, Vetiver, Cedro',
    duration: '6-8h',
    avoidTags: ['vetiver', 'polvo'],  // ← FIX: Violeta (polvo) + Vetiver en base
    sweetness: 3,
    freshness: 2,
    intensity: 3,
    emotionalDesc: 'El ejecutivo que también es aventurero. Clásico con carácter propio, versátil y siempre a la altura.',
  },
  {
    id: 'versace-eros',
    name: 'Eros',
    brand: 'Versace',
    gender: 'M',
    family: 'Oriental Fougère',
    occasions: ['noche', 'cita', 'verano'],
    feels: ['fresco', 'dulce', 'especiado'],
    topNotes: 'Menta, Manzana Verde, Limón',
    heartNotes: 'Haba Tonka, Geranio, Amor Amargo',
    baseNotes: 'Vainilla, Vetiver, Cedro',
    duration: '8-10h',
    avoidTags: ['dulce-intenso', 'vetiver'],  // ← FIX: Vetiver en base no estaba declarado
    sweetness: 4,
    freshness: 3,
    intensity: 4,
    emotionalDesc: 'El dios del amor embotellado. Fresco-dulce y absolutamente seductor. Una fragancia que promete mucho y cumple todo.',
  },

  // ── FEMENINOS ──────────────────────────────────────
  {
    id: '212-heroes-for-her',
    name: '212 Heroes For Her',
    brand: 'Carolina Herrera',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'trabajo', 'verano'],
    feels: ['floral', 'frutal', 'fresco'],
    topNotes: 'Pomelo, Pera, Frambuesa',
    heartNotes: 'Jazmín, Rosa, Flor de Lila',
    baseNotes: 'Sándalo, Almizcle suave',
    duration: '6-8h',
    avoidTags: [],
    sweetness: 3,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'Energía pura de mujer moderna. Fresca y frutal, para los días en que quieres comerte el mundo sin pedir permiso.',
  },
  {
    id: 'good-girl-blush',
    name: 'Good Girl Blush',
    brand: 'Carolina Herrera',
    gender: 'F',
    family: 'Floral Frutal Gourmand',
    occasions: ['noche', 'cita', 'evento'],
    feels: ['floral', 'dulce', 'frutal'],
    topNotes: 'Lichi, Pomelo',
    heartNotes: 'Rosa, Jazmín, Flor de Naranjo',
    baseNotes: 'Vainilla, Almendra, Vetiver',
    duration: '8-10h',
    avoidTags: ['dulce-intenso', 'vetiver'],  // ← FIX: Vetiver en base
    sweetness: 4,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Femenina con un secreto. La rosa que se convierte en vainilla al caer la noche. Inocente de día, irresistible de noche.',
  },
  {
    id: 'sun-gria',
    name: 'Sun-gria',
    brand: 'Lorenzo Pazzaglia',
    gender: 'F',
    family: 'Frutal Floral',
    occasions: ['verano', 'diario', 'cita'],
    feels: ['frutal', 'fresco', 'floral'],
    topNotes: 'Vino tinto, Naranja sanguina, Ciruela',
    heartNotes: 'Rosa, Jazmín',
    baseNotes: 'Patchouli, Cedro, Almizcle',
    duration: '7-9h',
    avoidTags: [],
    sweetness: 3,
    freshness: 3,
    intensity: 3,
    emotionalDesc: 'Una sangría de verano convertida en perfume. Frutal, viva y con personalidad propia. Perfecta para las tardes de sol.',
  },
  {
    id: 'coco-mademoiselle',
    name: 'Coco Mademoiselle',
    brand: 'Chanel',
    gender: 'F',
    family: 'Floral Oriental',
    occasions: ['trabajo', 'cita', 'evento', 'noche'],
    feels: ['floral', 'especiado', 'amaderado'],
    topNotes: 'Naranja, Bergamota',
    heartNotes: 'Rosa, Jazmín, Ylang-Ylang',
    baseNotes: 'Vetiver, Patchouli, Oud, Vainilla',
    duration: '8-10h',
    avoidTags: ['vetiver'],
    sweetness: 3,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'La mujer que sabe exactamente lo que quiere. Un clásico moderno redefinido para la mujer contemporánea y segura.',
  },
  {
    id: 'flower-bomb',
    name: 'Flowerbomb',
    brand: 'Viktor & Rolf',
    gender: 'F',
    family: 'Floral Gourmand',
    occasions: ['noche', 'cita', 'evento', 'invierno'],
    feels: ['floral', 'dulce', 'especiado'],
    topNotes: 'Bergamota, Té',
    heartNotes: 'Rosa, Jazmín, Orquídea, Freesia',
    baseNotes: 'Patchouli, Almizcle, Vainilla',
    duration: '10-12h',
    avoidTags: ['dulce-intenso', 'intenso'],
    sweetness: 5,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Una explosión de flores que nunca termina de sorprender. Intensa, envolvente y absolutamente imposible de ignorar.',
  },
  {
    id: 'black-opium',
    name: 'Black Opium',
    brand: 'Yves Saint Laurent',
    gender: 'F',
    family: 'Floral Gourmand',
    occasions: ['noche', 'cita', 'invierno'],
    feels: ['dulce', 'gourmand', 'floral'],
    topNotes: 'Grosella Negra, Pera',
    heartNotes: 'Café, Jazmín',
    baseNotes: 'Vainilla, Patchouli, Cedro',
    duration: '8-10h',
    avoidTags: ['dulce-intenso'],
    sweetness: 5,
    freshness: 1,
    intensity: 4,
    emotionalDesc: 'La noche con cafeína y vainilla. Para la mujer que vive con una intensidad que pocas se atreven a igualar.',
  },
  {
    id: 'la-vie-belle',
    name: 'La Vie Est Belle',
    brand: 'Lancôme',
    gender: 'F',
    family: 'Floral Gourmand',
    occasions: ['diario', 'cita', 'evento'],
    feels: ['floral', 'dulce', 'gourmand'],
    topNotes: 'Grosella Negra, Pera',
    heartNotes: 'Iris, Jazmín, Flor de Naranjo',
    baseNotes: 'Praline, Vainilla, Patchouli, Sándalo',
    duration: '8-10h',
    avoidTags: ['dulce-intenso', 'polvo'],  // Iris en corazón puede ser empolvado
    sweetness: 5,
    freshness: 1,
    intensity: 4,
    emotionalDesc: 'Una celebración embotellada. Cada nota es un brindis por la alegría de existir y de ser exactamente quien eres.',
  },
  {
    id: 'chance-chanel',
    name: 'Chance Eau Tendre',
    brand: 'Chanel',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'trabajo', 'verano'],
    feels: ['floral', 'fresco', 'frutal'],
    topNotes: 'Pomelo, Membrillo',
    heartNotes: 'Jacinto, Rosa',
    baseNotes: 'Iris, Cedro, Almizcle',
    duration: '6-8h',
    avoidTags: ['polvo'],  // ← FIX: Iris en base = empolvado para quienes lo rechazan
    sweetness: 2,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'Ligereza floral-frutal que envuelve como una nube de seda. Fresca, radiante y eternamente chic.',
  },
  {
    id: 'libre-ysl',
    name: 'Libre',
    brand: 'Yves Saint Laurent',
    gender: 'F',
    family: 'Floral Blanco Oriental',
    occasions: ['cita', 'noche', 'evento'],
    feels: ['floral', 'especiado', 'dulce'],
    topNotes: 'Mandarina, Petitgrain',
    heartNotes: 'Lavanda, Flor de Naranjo',
    baseNotes: 'Vainilla, Ámbar, Cedro',
    duration: '8-10h',
    avoidTags: [],
    sweetness: 3,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'La libertad tiene este olor. Floral y especiada, con una audacia que te hace dueña de tu propio destino.',
  },
  {
    id: 'mon-guerlain',
    name: 'Mon Guerlain',
    brand: 'Guerlain',
    gender: 'F',
    family: 'Floral Oriental',
    occasions: ['diario', 'cita', 'verano'],
    feels: ['floral', 'dulce', 'especiado'],
    topNotes: 'Bergamota, Lavanda',
    heartNotes: 'Lavanda, Jazmín Sambac',
    baseNotes: 'Vainilla Tahitiana, Sándalo, Almizcle',
    duration: '8-10h',
    avoidTags: ['dulce-intenso'],
    sweetness: 4,
    freshness: 2,
    intensity: 3,
    emotionalDesc: 'Lavanda y vainilla en perfecta armonía. Sensual sin ser pesada, tierna sin ser ingenua. Un abrazo en forma de perfume.',
  },
  {
    id: '212-vip-rose',
    name: '212 VIP Rosé',
    brand: 'Carolina Herrera',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['noche', 'cita', 'evento', 'verano'],
    feels: ['floral', 'frutal', 'dulce'],
    topNotes: 'Mandarina, Agua de rosas',
    heartNotes: 'Rosa, Gardenia',
    baseNotes: 'Almizcle, Madera de cedro',
    duration: '6-8h',
    avoidTags: [],
    sweetness: 3,
    freshness: 3,
    intensity: 3,
    emotionalDesc: 'La fiesta antes de que empiece. Alegre, luminosa y coqueta. Para la mujer que sabe que ella es el plan.',
  },
  {
    id: 'good-girl-ch',
    name: 'Good Girl',
    brand: 'Carolina Herrera',
    gender: 'F',
    family: 'Floral Oriental',
    occasions: ['noche', 'cita', 'evento', 'invierno'],
    feels: ['floral', 'dulce', 'especiado'],
    topNotes: 'Almendra, Café, Bergamota',
    heartNotes: 'Jazmín Sambac, Tuberosa',
    baseNotes: 'Cacao, Tonka, Vetiver',
    duration: '10-12h',
    avoidTags: ['dulce-intenso', 'vetiver', 'intenso'],  // ← FIX: Vetiver + muy intensa
    sweetness: 5,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Dos caras: la buena y la que disfruta no serlo. Sus notas de café y almendra ya cuentan toda la historia que necesitas saber.',
  },
  {
    id: 'omnia-bvlgari',
    name: 'Omnia Crystalline',
    brand: 'Bvlgari',
    gender: 'F',
    family: 'Floral Acuático',
    occasions: ['diario', 'trabajo', 'verano'],
    feels: ['floral', 'fresco', 'acuatico'],
    topNotes: 'Bambú, Nenúfar',
    heartNotes: 'Peony, Lotus, Magnolia',
    baseNotes: 'Cedro, Almizcle',
    duration: '5-7h',
    avoidTags: ['pesado'],
    sweetness: 1,
    freshness: 5,
    intensity: 2,
    emotionalDesc: 'Transparente como el agua, pura como el cristal. Para la mujer que prefiere el susurro elegante al grito innecesario.',
  },
  {
    id: 'euphoria-calvin',
    name: 'Euphoria',
    brand: 'Calvin Klein',
    gender: 'F',
    family: 'Floral Oriental',
    occasions: ['noche', 'cita', 'invierno'],
    feels: ['floral', 'especiado', 'amaderado'],
    topNotes: 'Granada, Persimón',
    heartNotes: 'Orquídea Negra, Loto',
    baseNotes: 'Madera de Sándalo, Cachemira, Musgo',
    duration: '8-10h',
    avoidTags: ['intenso'],  // ← FIX: Oriental intensa, no apta para quienes buscan discreción
    sweetness: 3,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'Sensualidad oscura y sofisticada. Una fragancia que dice todo lo que las palabras no pueden y que no necesita explicación.',
  },
  {
    id: 'si-giorgio',
    name: 'Sì',
    brand: 'Giorgio Armani',
    gender: 'F',
    family: 'Chypre Frutal',
    occasions: ['trabajo', 'cita', 'diario'],
    feels: ['floral', 'frutal', 'amaderado'],
    topNotes: 'Grosella Negra, Mandarina',
    heartNotes: 'Rosa, Neroli, Freesia',
    baseNotes: 'Patchouli, Ámbar, Vainilla, Sándalo',
    duration: '8-10h',
    avoidTags: [],
    sweetness: 3,
    freshness: 2,
    intensity: 4,
    emotionalDesc: 'El consentimiento de ser tú misma, siempre. Un chypre elegante para la mujer que lidera sin esfuerzo aparente.',
  },
  {
    id: 'daisy-mj',
    name: 'Daisy',
    brand: 'Marc Jacobs',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'verano', 'trabajo'],
    feels: ['floral', 'frutal', 'fresco'],
    topNotes: 'Fresa silvestre, Violeta',
    heartNotes: 'Gardenia, Violeta, Flor de Manzano',
    baseNotes: 'Sándalo blanco, Vainilla, Musgo',
    duration: '6-8h',
    avoidTags: ['polvo'],  // ← FIX: Violeta prominente = empolvado
    sweetness: 3,
    freshness: 3,
    intensity: 3,
    emotionalDesc: 'Alegría botánica destilada. Para las mañanas de domingo, los comienzos de primavera y los días que merecen celebrarse.',
  },
];
