import type { Perfume } from '../types';

export const unoAUno: Perfume[] = [
  {
    id: '1.1_silver_mountain',
    name: 'Silver Mountain',
    brand: 'Creed (1.1)',
    gender: 'U',
    family: 'Aromática',
    occasions: ['diario', 'trabajo', 'verano'],
    feels: ['fresco', 'citrico', 'acuatico'],
    topNotes: 'Bergamota, Mandarina',
    heartNotes: 'Té verde, Grosellas negras',
    baseNotes: 'Almizcle, Petit grain, Sándalo',
    duration: '6-8h',
    avoidTags: ['dulce', 'oud'],
    sweetness: 1,
    freshness: 5,
    intensity: 3,
    emotionalDesc: 'Una brisa glaciar en los Alpes. Refrescante, limpia y vigorizante.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_imagination',
    name: 'Imagination',
    brand: 'Louis Vuitton (1.1)',
    gender: 'M',
    family: 'Cítrica Aromática',
    occasions: ['diario', 'trabajo', 'verano'],
    feels: ['fresco', 'citrico', 'especiado'],
    topNotes: 'Cidra, Bergamota de Calabria, Naranja dulce',
    heartNotes: 'Té negro de China, Canela, Jengibre nigeriano',
    baseNotes: 'Ambroxan, Madera de gaiac, Incienso',
    duration: '8h+',
    avoidTags: ['oud', 'empalagoso'],
    sweetness: 2,
    freshness: 5,
    intensity: 3,
    emotionalDesc: 'El despertar luminoso. Un contraste audaz de té negro y cítricos infinitos.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_ombre_nomada',
    name: 'Ombre Nomade',
    brand: 'Louis Vuitton (1.1)',
    gender: 'U',
    family: 'Ámbar Amaderada',
    occasions: ['noche', 'evento', 'invierno'],
    feels: ['oud', 'amaderado', 'especiado'],
    topNotes: 'Frambuesa, Geranio',
    heartNotes: 'Rosa, Azafrán, Incienso',
    baseNotes: 'Madera de Oud, Madera de abedul, Benjuí',
    duration: '12h+',
    avoidTags: ['fresco', 'citrico', 'acuatico'],
    sweetness: 2,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Un viaje al desierto al anochecer. Oud majestuoso y místico envuelto en cuero y frambuesa.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_asad_lattafa',
    name: 'Asad',
    brand: 'Lattafa (1.1)',
    gender: 'M',
    family: 'Ámbar Especiada',
    occasions: ['noche', 'cita', 'invierno'],
    feels: ['especiado', 'amaderado', 'dulce'],
    topNotes: 'Pimienta negra, Piña, Tabaco',
    heartNotes: 'Café, Patchouli, Iris',
    baseNotes: 'Ámbar, Vainilla, Maderas secas',
    duration: '8h+',
    avoidTags: ['floral_suave', 'acuatico'],
    sweetness: 3,
    freshness: 1,
    intensity: 4,
    emotionalDesc: 'Audaz e imponente. Un especiado cálido con carácter oscuro y elegante.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_bharara_king',
    name: 'King',
    brand: 'Bharara (1.1)',
    gender: 'M',
    family: 'Aromática Frutal',
    occasions: ['diario', 'evento', 'cita'],
    feels: ['frutal', 'dulce', 'fresco'],
    topNotes: 'Naranja, Limón, Bergamota',
    heartNotes: 'Notas afrutadas dulces',
    baseNotes: 'Vainilla, Almizcle blanco, Ámbar',
    duration: '10h+',
    avoidTags: ['oud_fuerte', 'verde_amargo'],
    sweetness: 4,
    freshness: 3,
    intensity: 4,
    emotionalDesc: 'Una bomba frutal y dulce que roba miradas en cualquier fiesta o encuentro.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_khamrah_dukhan',
    name: 'Khamrah Dukhan',
    brand: 'Lattafa (1.1)',
    gender: 'U',
    family: 'Ámbar Especiada',
    occasions: ['noche', 'invierno', 'cita'],
    feels: ['dulce', 'gourmand', 'especiado'],
    topNotes: 'Canela, Nuez moscada, Bergamota',
    heartNotes: 'Dátiles, Praliné, Nardos, Mahonial',
    baseNotes: 'Vainilla, Haba tonka, Amberwood, Mirra',
    duration: '10h+',
    avoidTags: ['fresco', 'citrico'],
    sweetness: 5,
    freshness: 1,
    intensity: 4,
    emotionalDesc: 'Como un coñac añejo con dátiles endulzados. Una experiencia rica y envolvente.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_amber_rouge',
    name: 'Amber Rouge',
    brand: 'Orientica (1.1)',
    gender: 'U',
    family: 'Ámbar Amaderada',
    occasions: ['evento', 'noche', 'cita'],
    feels: ['dulce', 'amaderado', 'especiado'],
    topNotes: 'Azafrán, Jazmín',
    heartNotes: 'Amberwood, Ámbar gris',
    baseNotes: 'Cedro, Resina de abeto',
    duration: '10h+',
    avoidTags: ['citrico', 'acuatico'],
    sweetness: 4,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'La esencia del lujo. Un resplandor de azúcar quemada flotando sobre maderas preciosas.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_set_regalo_moschino',
    name: 'Set de Regalo',
    brand: 'Moschino (1.1)',
    gender: 'F',
    family: 'Floral Frutal',
    occasions: ['diario', 'verano', 'trabajo'],
    feels: ['fresco', 'floral', 'frutal'],
    topNotes: 'Mandarina, Manzana Granny Smith, Magnolia',
    heartNotes: 'Peonía, Grosella blanca, Jazmín',
    baseNotes: 'Sándalo, Amberwood, Almizcle',
    duration: '6-8h',
    avoidTags: ['oud_fuerte', 'oscuro'],
    sweetness: 3,
    freshness: 4,
    intensity: 3,
    emotionalDesc: 'Juventud, juego y vitalidad. Un set que irradia alegría chispeante.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_good_girl',
    name: 'Good Girl',
    brand: 'Carolina Herrera (1.1)',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['noche', 'cita', 'evento'],
    feels: ['dulce', 'floral', 'gourmand'],
    topNotes: 'Almendra, Café, Bergamota, Limón',
    heartNotes: 'Nardos, Jazmín sambac, Flor de azahar',
    baseNotes: 'Haba tonka, Cacao, Vainilla, Praliné',
    duration: '8h+',
    avoidTags: ['verde', 'acuatico'],
    sweetness: 4,
    freshness: 1,
    intensity: 4,
    emotionalDesc: 'Dualidad seductora. Empoderada, misteriosa e irresistiblemente sensual.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_delina',
    name: 'Delina',
    brand: 'Parfums de Marly (1.1)',
    gender: 'F',
    family: 'Floral',
    occasions: ['diario', 'cita', 'evento'],
    feels: ['floral', 'frutal', 'fresco'],
    topNotes: 'Lichi, Ruibarbo, Bergamota, Nuez moscada',
    heartNotes: 'Rosa turca, Peonía, Almizcle, Petalia, Vainilla',
    baseNotes: 'Cachemira, Cedro, Incienso',
    duration: '10h+',
    avoidTags: ['oud_fuerte', 'masculino'],
    sweetness: 3,
    freshness: 3,
    intensity: 4,
    emotionalDesc: 'La reina de las rosas. Majestuosa, romántica, bailando entre el dulce y el ácido del lichi.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_cloud_2_0',
    name: 'Cloud 2.0 Intense',
    brand: 'Ariana Grande (1.1)',
    gender: 'F',
    family: 'Ámbar Vainilla',
    occasions: ['diario', 'cita', 'invierno'],
    feels: ['gourmand', 'dulce', 'amaderado'],
    topNotes: 'Lavanda, Pera, Bergamota',
    heartNotes: 'Crema batida, Praliné, Coco, Orquídea',
    baseNotes: 'Cachemira, Ambroxan, Almizcle, Notas amaderadas',
    duration: '8h+',
    avoidTags: ['floral_blanco', 'verde'],
    sweetness: 5,
    freshness: 1,
    intensity: 4,
    emotionalDesc: 'Una nube de praliné cremoso y maderas. Más profunda, misteriosa y adictiva.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_profumo',
    name: 'Acqua Di Giò Profumo',
    brand: 'Armani (1.1)',
    gender: 'M',
    family: 'Aromática Acuática',
    occasions: ['diario', 'trabajo', 'evento'],
    feels: ['acuatico', 'fresco', 'amaderado'],
    topNotes: 'Notas marinas, Bergamota',
    heartNotes: 'Romero, Salvia, Geranio',
    baseNotes: 'Incienso, Pachulí',
    duration: '8h+',
    avoidTags: ['dulce_empalagoso', 'gourmand'],
    sweetness: 1,
    freshness: 4,
    intensity: 4,
    emotionalDesc: 'Olas chocando contra rocas oscuras. Sofisticación acuática con un aura ahumada de incienso.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_starwalker',
    name: 'Starwalker',
    brand: 'Montblanc (1.1)',
    gender: 'M',
    family: 'Amaderada Especiada',
    occasions: ['diario', 'trabajo', 'verano'],
    feels: ['fresco', 'amaderado', 'citrico'],
    topNotes: 'Bambú, Bergamota, Mandarina',
    heartNotes: 'Sándalo, Almizcle blanco, Cedro',
    baseNotes: 'Jengibre, Resina de abeto, Nuez moscada',
    duration: '6h',
    avoidTags: ['pesado', 'oud', 'invierno'],
    sweetness: 1,
    freshness: 5,
    intensity: 2,
    emotionalDesc: 'Claridad mental y paz. Es como caminar por un bosque de bambú al amanecer.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_one_million',
    name: '1 Million',
    brand: 'Paco Rabanne (1.1)',
    gender: 'M',
    family: 'Amaderada Especiada',
    occasions: ['noche', 'evento', 'invierno'],
    feels: ['dulce', 'especiado', 'amaderado'],
    topNotes: 'Mandarina roja, Pomelo, Menta',
    heartNotes: 'Canela, Notas especiadas, Rosa',
    baseNotes: 'Ámbar, Cuero, Notas amaderadas, Pachulí hindú',
    duration: '8h+',
    avoidTags: ['acuatico', 'fresco'],
    sweetness: 4,
    freshness: 1,
    intensity: 4,
    emotionalDesc: 'Mucha presencia, fiesta y atracción. Oro líquido rebosante de canela, cuero y especias.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_club_de_nuit',
    name: 'Club de Nuit Intense',
    brand: 'Armaf (1.1)',
    gender: 'M',
    family: 'Amaderada Especiada',
    occasions: ['diario', 'trabajo', 'evento'],
    feels: ['citrico', 'amaderado', 'fresco'],
    topNotes: 'Limón, Piña, Bergamota, Grosellas negras, Manzana',
    heartNotes: 'Abedul, Jazmín, Rosa',
    baseNotes: 'Almizcle, Ámbar gris, Pachulí, Vainilla',
    duration: '10h+',
    avoidTags: ['oud', 'femenino'],
    sweetness: 2,
    freshness: 4,
    intensity: 5,
    emotionalDesc: 'Impacto total. Una salida cítrica punzante que evoluciona hacia una madera de abedul ahumada e implacable.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_swiss_army',
    name: 'Swiss Army',
    brand: 'Victorinox (1.1)',
    gender: 'M',
    family: 'Amaderada Aromática',
    occasions: ['diario', 'verano', 'trabajo'],
    feels: ['fresco', 'verde', 'citrico'],
    topNotes: 'Menta, Notas verdes, Yuzu, Bergamota',
    heartNotes: 'Romero, Lavanda, Hojas de violeta',
    baseNotes: 'Ciprés, Bálsamo de abeto, Cedro',
    duration: '6-8h',
    avoidTags: ['dulce', 'oscuro'],
    sweetness: 1,
    freshness: 5,
    intensity: 2,
    emotionalDesc: 'Aire puro de montañas nevadas. Verde, limpio, herbal y supremamente revitalizante.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_sauvage_elixir',
    name: 'Sauvage Elixir',
    brand: 'Dior (1.1)',
    gender: 'M',
    family: 'Aromática',
    occasions: ['noche', 'evento', 'invierno'],
    feels: ['especiado', 'amaderado', 'oud'],
    topNotes: 'Nuez moscada, Canela, Cardamomo, Pomelo',
    heartNotes: 'Lavanda, Cumarina',
    baseNotes: 'Regaliz, Sándalo, Ámbar, Pachulí',
    duration: '12h+',
    avoidTags: ['fresco_suave', 'acuatico'],
    sweetness: 2,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Poder puro concentrado en una poción. Lavanda nocturna bañada en especias cálidas y licorosas.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_la_vida_es_bella',
    name: 'La Vie Est Belle',
    brand: 'Lancôme (1.1)',
    gender: 'F',
    family: 'Floral Frutal Gourmand',
    occasions: ['diario', 'cita', 'evento'],
    feels: ['dulce', 'gourmand', 'floral'],
    topNotes: 'Grosellas negras, Pera',
    heartNotes: 'Iris, Jazmín, Flor de azahar del naranjo',
    baseNotes: 'Praliné, Vainilla, Pachulí, Haba tonka',
    duration: '10h+',
    avoidTags: ['fresco_fuerte', 'acuatico'],
    sweetness: 5,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'La felicidad embotellada. Un praliné radiante, abrazado por elegancia de iris y vainilla.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_khamrah',
    name: 'Khamrah',
    brand: 'Lattafa (1.1)',
    gender: 'U',
    family: 'Ámbar Especiada',
    occasions: ['noche', 'invierno', 'cita'],
    feels: ['dulce', 'gourmand', 'especiado'],
    topNotes: 'Canela, Nuez moscada, Bergamota',
    heartNotes: 'Dátiles, Praliné, Nardos',
    baseNotes: 'Vainilla, Haba tonka, Amberwood',
    duration: '10h+',
    avoidTags: ['citrico', 'verde'],
    sweetness: 5,
    freshness: 1,
    intensity: 4,
    emotionalDesc: 'Postre celestial en invierno. Miel, dátiles y maderas ambaradas sumamente acogedoras.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_asad_bourbon',
    name: 'Asad Bourbon',
    brand: 'Lattafa (1.1)',
    gender: 'M',
    family: 'Ámbar Vainilla',
    occasions: ['noche', 'cita', 'invierno'],
    feels: ['dulce', 'especiado', 'amaderado'],
    topNotes: 'Pimienta, Vainilla',
    heartNotes: 'Coñac, Lavanda',
    baseNotes: 'Maderas secas, Ámbar',
    duration: '8h+',
    avoidTags: ['floral', 'fresco_acuatico'],
    sweetness: 4,
    freshness: 1,
    intensity: 4,
    emotionalDesc: 'Misterio licoroso. La fuerza del Asad original sumergida en un barril de bourbon avainillado.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_orientica_rouge',
    name: 'Royal Rouge',
    brand: 'Orientica (1.1)',
    gender: 'F',
    family: 'Floral Amaderada',
    occasions: ['evento', 'cita', 'noche'],
    feels: ['dulce', 'amaderado', 'floral'],
    topNotes: 'Almendra amarga, Azafrán',
    heartNotes: 'Jazmín egipcio, Cedro',
    baseNotes: 'Ámbar gris, Notas amaderadas, Almizcle',
    duration: '10h+',
    avoidTags: ['citrico_fuerte', 'acuatico'],
    sweetness: 4,
    freshness: 1,
    intensity: 4,
    emotionalDesc: 'Lujo carmesí. Un aroma sofisticado, envolvente, con un toque adictivo a almendra quemada.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_360_hombre',
    name: '360 for Men',
    brand: 'Perry Ellis (1.1)',
    gender: 'M',
    family: 'Aromática',
    occasions: ['diario', 'trabajo', 'verano'],
    feels: ['fresco', 'citrico', 'acuatico'],
    topNotes: 'Bayas de enebro, Limón, Bergamota',
    heartNotes: 'Lavanda, Salvia, Cardamomo, Fresia',
    baseNotes: 'Notas amaderadas, Vetiver, Almizcle',
    duration: '6-8h',
    avoidTags: ['dulce', 'gourmand'],
    sweetness: 1,
    freshness: 5,
    intensity: 3,
    emotionalDesc: 'Pulcritud clásica. La definición perfecta del hombre recién salido de la ducha.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_club_de_nuit_untold',
    name: 'Club de Nuit Untold',
    brand: 'Armaf (1.1)',
    gender: 'U',
    family: 'Ámbar Amaderada',
    occasions: ['evento', 'noche', 'cita'],
    feels: ['dulce', 'amaderado', 'gourmand'],
    topNotes: 'Azafrán, Jazmín',
    heartNotes: 'Amberwood, Ámbar gris',
    baseNotes: 'Resina de abeto, Cedro',
    duration: '10h+',
    avoidTags: ['citrico', 'verde'],
    sweetness: 4,
    freshness: 1,
    intensity: 5,
    emotionalDesc: 'Opulencia mágica de azúcar, algodón y maderas. Elegancia inolvidable que llena la habitación.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_miss_dior',
    name: 'Miss Dior',
    brand: 'Dior (1.1)',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['diario', 'cita', 'evento'],
    feels: ['floral', 'dulce', 'frutal'],
    topNotes: 'Lirio de los valles, Peonía, Iris',
    heartNotes: 'Rosa centifolia, Melocotón, Albaricoque',
    baseNotes: 'Vainilla, Haba tonka, Almizcle, Benjuí',
    duration: '8h',
    avoidTags: ['masculino', 'oud'],
    sweetness: 3,
    freshness: 2,
    intensity: 3,
    emotionalDesc: 'Un ramillete lujoso y sedoso, bordado con vainilla sublime.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_aqua_di_gio',
    name: 'Acqua Di Giò',
    brand: 'Armani (1.1)',
    gender: 'M',
    family: 'Aromática Acuática',
    occasions: ['diario', 'verano', 'trabajo'],
    feels: ['acuatico', 'fresco', 'citrico'],
    topNotes: 'Lima, Limón, Bergamota, Jazmín, Naranja, Mandarina, Neroli',
    heartNotes: 'Notas marinas, Jazmín, Calone, Melocotón, Fresia, Jacinto, Romero',
    baseNotes: 'Almizcle blanco, Cedro, Musgo de roble, Pachulí, Ámbar',
    duration: '6h',
    avoidTags: ['dulce', 'invierno'],
    sweetness: 1,
    freshness: 5,
    intensity: 3,
    emotionalDesc: 'La libertad del océano. Un equilibrio perfecto de brisa marina amarga y cítricos italianos.',
    version: '1.1',
    isLimited: true
  },
  {
    id: '1.1_ch_women',
    name: 'CH',
    brand: 'Carolina Herrera (1.1)',
    gender: 'F',
    family: 'Ámbar Floral',
    occasions: ['diario', 'trabajo', 'cita'],
    feels: ['dulce', 'floral', 'citrico'],
    topNotes: 'Fruta tropical, Bergamota, Pomelo, Limón de Amalfi, Notas acuáticas',
    heartNotes: 'Praliné, Canela, Flor del naranjo africano, Jazmín, Tintura de rosas',
    baseNotes: 'Gamuza, Pachulí, Cachemira, Sándalo, Almizcle, Cedro de Virginia, Ámbar',
    duration: '8h',
    avoidTags: ['oud_pesado', 'unisex'],
    sweetness: 4,
    freshness: 2,
    intensity: 3,
    emotionalDesc: 'Elegancia y simpatía natural. Citricos iniciales que bajan a un fondo de cuero, praliné y flores femeninas.',
    version: '1.1',
    isLimited: true
  }
];
